### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by Thrillberg** [rubyforgood/pet-rescue#1]
Some things to include:
- What skills we're looking for (StimulusJS, anything else?)
- More info about Ruby for Good
- How to contribute
- Review setup, make sure it works
- Anything else you want to add!

**Comment by edwinthinks** [comment]
I think the README could move some information to a Wiki on GH. I personally like to make the README very short and optimize for getting the local machine setup. Happy to open a PR for this :)
