### ISSUE TITLE
Adopter Foster Dashboard: Remove sample button

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#1001]
Log in as an adopter and go to the dashboard and you will see this redundant button - please remove it

<img width="1321" alt="image" src="https://github.com/user-attachments/assets/ad88cb6d-2ad9-4d04-9a5f-a45aca11d53c">

**Comment by italomatos** [comment]
Hey @kasugaijin can you assign to me ? 
thankss

**Comment by italomatos** [comment]
PR 🚀🚀
https://github.com/rubyforgood/pet-rescue/pull/1002
