### ISSUE TITLE
Staff dashboard: update custom page icon

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#1017]
Please change the icon for Custom Page in the sidenav to `fe-layout`
![image](https://github.com/user-attachments/assets/6f827e36-8118-4d39-8a42-4037c14deecd)

See: https://geeksui.codescandy.com/geeks/pages/dashboard/admin-course-overview.html

**Comment by wuletawwonte** [comment]
Hi @kasugaijin 
I would like to work on this issue.
