### ISSUE TITLE
Org Root Page: remove the additional links section

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#1018]
Please remove this section from the Organization scoped root page - we do not need this for MVP
![image](https://github.com/user-attachments/assets/8c1dfa05-5fab-4025-a03f-6104ac6b1179)

**Comment by wuletawwonte** [comment]
Hi, I would like to work on this issue.

**Comment by kasugaijin** [comment]
@wuletawwonte all yours!
