### ISSUE TITLE
Pet: Refactor instance method to use the Match model instead of the AdopterApplication model

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#1021]
We have this instance method on `Pet`

  def is_adopted?
    adopter_applications.any? { |app| app.status == "adoption_made" }
  end

The single source of truth on an adoption should be the `Match` model, where the `match_type` is `adoption`. Please update the method to query the pet's matches instead.

**Comment by coalest** [comment]
@kasugaijin I can take this
