### ISSUE TITLE
AdopterApplication: Add unique constraint on model and database

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#1024]
We should prevent a given adopter from being able to make more than one adopter application on a given pet. 

So, please add a validation on `AdopterApplication` that will check for uniqueness on `form_submission_id` and `pet_id` and prevent creation of a record if this validation fails.

Please also add a migration to create an index that will also enforce this on the database. You can wrap the migration changes in the safety assured block so it won't upset strong migrations gem (see other recent migrations).

**Comment by coalest** [comment]
Can I take this task?

**Comment by kasugaijin** [comment]
@coalest all yours
