### ISSUE TITLE
View Translations: look in the adopter fosterer scope for any remaining text not using translation file

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#1025]
Please review the view files in the `Organizations::AdopterFosterer` scope to see if any are using plain strings in the view, and refactor these to use a value from `en.yml`. You may be able to leverage existing entries, and if you have to make new ones, please follow the existing structure in `en.yml`

**Comment by wuletawwonte** [comment]
I would like to work on this
