### ISSUE TITLE
Inconsistent date time formatting on the manage fosters page

### ISSUE THREAD

**Issue by basil-gray** [rubyforgood/pet-rescue#1026]
1. Log in as a staff and navigate to the Fosters page.
2. Observe that the button when modifying a date uses mmddyyyy
3. It then displays in ddmmyyyy when you click on it.

![Screenshot 2024-10-02 at 16 49 45](https://github.com/user-attachments/assets/3b1cbc04-5851-4dbf-97d1-9c8cb79d3d9e)
![Screenshot 2024-10-02 at 16 49 49](https://github.com/user-attachments/assets/24c14e51-23bc-40d5-bb81-e25e8603248a)

There's a strftime on the below page where the format is specified.

app/views/organizations/staff/manage_fosters/_foster_table_row.html.erb

**Comment by basil-gray** [comment]
@kasugaijin can you confirm what date format we can use throughout the application?

Might be a good first bug too.

**Comment by kasugaijin** [comment]
@basil-gray good catch! I prefer dd mm yyyy

**Comment by wandergithub** [comment]
I can fix this.

**Comment by kasugaijin** [comment]
@wandergithub all yours

**Comment by wandergithub** [comment]
I can't reproduce this. It keeps mm dd yyyy no matter what I do.

**Comment by kasugaijin** [comment]
Ah it could be browser dependent. If that is the case...we can just ignore this.
