### ISSUE TITLE
Add dependabot

### ISSUE THREAD

**Issue by nsiwnf** [rubyforgood/pet-rescue#11]
Add a [dependabot github action workflow ](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions#common-dependabot-automations) to ensure we are up to date with the latest versions.

**Comment by Thrillberg** [comment]
@nsiwnf I've started poking around at this and I'm a little confused. My understanding is that dependabot already will open PRs when vulnerabilities are detected or dependencies are out of date. The change in the link you provided would give us extra metadata about the open PR, is that right? I'm not sure that we need it or what benefit the metadata gets us.

**Comment by nsiwnf** [comment]
We have to add the dependabot yml to configure how often it runs and what packages to check (rails, npm etc) - as of right now, it will not open any PRs

**Comment by Thrillberg** [comment]
Oh funny, maybe dependabot changed its behavior? I have another open source repo that it opens PRs on and there is no configuration to enable it. GitHub just does it. I'll look into it more...
