### ISSUE TITLE
2 broken links in CONTRIBUTING.md

### ISSUE THREAD

**Issue by egemen-dev** [rubyforgood/pet-rescue#117]
There are 2 broken links in [CONTRIBUTING.md](https://github.com/rubyforgood/pet-rescue/blob/main/CONTRIBUTING.md)

First one:
> Here are the basic steps to submit a pull request. Make sure that you're working on an [open issue](https://github.com/orgs/rubyforgood/projects/10/views/1)–if the relevant issue doesn't exist, open it!
> 

Second one:
> 2. Claim an issue on [our issue tracker](https://github.com/orgs/rubyforgood/projects/10/views/1)

**Comment by egemen-dev** [comment]
I'm not sure what the correct links are.

**Comment by Eduardo06sp** [comment]
Related: #12 

Honestly not sure what happened to that, I did see it for a while

**Comment by nsiwnf** [comment]
Thanks for catching!
