### ISSUE TITLE
Create RFG project

### ISSUE THREAD

**Issue by nsiwnf** [rubyforgood/pet-rescue#12]
Request [new project](https://github.com/orgs/rubyforgood/projects) for RFG 2023

**Comment by edwinthinks** [comment]
@nsiwnf - I created the board and added you as the admin: https://github.com/rubyforgood/pet-rescue/projects?query=is%3Aopen

**Comment by Thrillberg** [comment]
ooo I've never used GH Projects before. Curious to see how it works!

**Comment by edwinthinks** [comment]
I think now that we have it, I'll close this issue.
