### ISSUE TITLE
Remove active admin

### ISSUE THREAD

**Issue by Thrillberg** [rubyforgood/pet-rescue#13]
We're currently using a gem, [active_admin](https://activeadmin.info/), which is deemed to be more trouble than it's worth. We would like to remove this gem. In a future issue, we can spell out how to replace it with something more suited to our needs.

**Comment by Eduardo06sp** [comment]
I would like to take this unless you prefer to have a replacement in place before removing it.

There is a notable amount of code associated with removing `active_admin`, which I would also delete as part of this Issue.

**Comment by Thrillberg** [comment]
@Eduardo06sp Yes please take this one if you want! We don't have a replacement yet but I _think_ that's ok. Do you both agree @nsiwnf and @edwinthinks ?

**Comment by Thrillberg** [comment]
@Eduardo06sp Just wanted to check in to see if you are still working on this one. No pressure and no rush but wanted to check in case I or someone else should take it on. 😄

**Comment by edwinthinks** [comment]
Sorry @Thrillberg for the late reply. I think its good that we remove this. Imo anything that doesn't have a clear purpose or job to be done -- should be removed. It seems like active admin is one of those tools right now for us :).

Maybe we'll bring it back someday in the future with more context and information to power that decision. But yeh for now let's get rid of it.

**Comment by Eduardo06sp** [comment]
@Thrillberg honestly, I haven't started at all. I didn't want to start in case you wanted to build a custom dashboard first. You can take it if you would like.

I was working on a personal project. I'll go ahead and assign myself to other open issues, time permitting.

**Comment by marlena-b** [comment]
Hey @Thrillberg @edwinthinks, I'm happy to help with this. Can I get assigned, please?

**Comment by edwinthinks** [comment]
Its your @marlena-b :)

**Comment by marlena-b** [comment]
@edwinthinks thank you! I have a fix ready but looks like I cannot push my changes:
```
> git push --set-upstream origin remove-active-admin

ERROR: Permission to rubyforgood/pet-rescue.git denied to marlena-b.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I followed the instructions in [the contributing guide](https://github.com/rubyforgood/pet-rescue/blob/main/CONTRIBUTING.md). Do I need to get any additional permissions or is there something wrong on my end?

**Comment by edwinthinks** [comment]
@marlena-b ahh yes, let me make sure to add you to this repo. FYI, you could push up the PR to your own fork and open the PR into this next time.

One moment!

**Comment by edwinthinks** [comment]
@marlena-b you have access now. looking forward to seeing your PR :)
