### ISSUE TITLE
Use hotwire for Country / State dropdown

### ISSUE THREAD

**Issue by nsiwnf** [rubyforgood/pet-rescue#141]
See #94 and #136 for reference

This has been implemented in JS, as a better standard moving forward, let's reuse turbo-form and hotwire components to get the same functionality while keeping things more maintainable

**Resources**
https://www.youtube.com/watch?v=ReZS6wfh3lo
https://github.com/thecodecrate/city-state#all-countries-of-the-world

**Comment by egemen-dev** [comment]
Merged
