### ISSUE TITLE
Add pundit gem

### ISSUE THREAD

**Issue by Thrillberg** [rubyforgood/pet-rescue#15]
We want to make use of the [pundit gem](https://github.com/varvet/pundit). Please add it to the Gemfile, run the install command, and familiarize yourself with it (whoever takes this ticket de facto becomes our pundit authority!).

For context, we imagine using this to distinguish between three different roles, listed here in increasing levels of access:
- adopter - the end users
- staff - the people who work at the organization's rescue
- admin - the people who work on the code of the app (ie, Ben and RfG folks)

**Comment by Thrillberg** [comment]
I added the `on hold` label to this issue because I think depending on how @johnksawers's and @jadekstewart3 's work on the `User` model turns out, we might have a different idea on how to proceed with roles and permissions. Maybe we won't need pundit?

**Comment by edwinthinks** [comment]
Removing on-hold on this, I think we can add this in safetly now :)

**Comment by edwinthinks** [comment]
@heyapricot you can take on this again if you want :)

**Comment by heyapricot** [comment]
@edwinthinks Some things have changed since the last time I saw the app. 
Do we have user stories of sorts?
I'm thinking:
As a staff user I should be able to open page(s) X
As a regular user I should not be able to open page(s) x

**Comment by kasugaijin** [comment]
Closed as we are using Rolify to manage user roles right now.
