### ISSUE TITLE
Internationalize validation error messages

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#153]
A message is displayed in the UI if a model fails a validation. These errors should be added to translation files so we can display them in different languages depending on the locale.

**Comment by kasugaijin** [comment]
I can take this on.

**Comment by DreamVenerable** [comment]
I'd like to take this issue

**Comment by DreamVenerable** [comment]
@kasugaijin How do I structure the errors in en.yml?

For example, AdopterAccount model has one validation error, where do I place that?

**Comment by kasugaijin** [comment]
Hey! Does this article help? https://medium.com/@jelaniwoods/i18n-validation-errors-a634bbc5fb1a

**Comment by DreamVenerable** [comment]
Yup, thanks!
