### ISSUE TITLE
Organization Image Upload

### ISSUE THREAD

**Issue by jadekstewart3** [rubyforgood/pet-rescue#164]
As an organization admin, when I visit `/organization_profile/edit`
-  I can upload an image and see a thumbnail
- I can delete the image
- I get an error if the file is not an image extension e.g. it's a .pdf

See `/users/edit` for an idea of what is required.

**Comment by jp524** [comment]
I would like to work on this!

**Comment by DreamVenerable** [comment]
I'd also like to take this issue in case no one does

**Comment by edwinthinks** [comment]
Sorry for the late reply, catching up on things! @jp524 are you still available to take this.

@DreamVenerable sorry again about preference, since @jp524 asked first I'll ask first for them to take it. Otherwise I'll assign you if they don't.

**Comment by DreamVenerable** [comment]
Haha no problem, was expecting that, I just commented to be second in line :)

**Comment by jp524** [comment]
@edwinthinks Yes I’m still available to work on this

**Comment by jp524** [comment]
Hi @jadekstewart3 & @kasugaijin, I saw in the `organization_profiles/_form` view partial that there is a template in place for avatars. My understanding is that avatars are separate from this issue, and that the organization image would be used in place where the `Brand logo` is called (such as in the `dashboard/_navbar` partial). Is that correct?

**Comment by kasugaijin** [comment]
> Hi @jadekstewart3 & @kasugaijin, I saw in the `organization_profiles/_form` view partial that there is a template in place for avatars. My understanding is that avatars are separate from this issue, and that the organization image would be used in place where the `Brand logo` is called (such as in the `dashboard/_navbar` partial). Is that correct?

Ah good question @jp524. Do you think it would make sense for this upload to be used in both cases? I could see a logo being a useful avatar as well as used for branding.

**Comment by jp524** [comment]
> Ah good question @jp524. Do you think it would make sense for this upload to be used in both cases? I could see a logo being a useful avatar as well as used for branding.

I think the upload of the logo and avatar would be built almost identically. Is someone already working on implementing avatars though?

**Comment by kasugaijin** [comment]
@jp524 that work is complete. Recently merged: https://github.com/rubyforgood/pet-rescue/pull/401
