### ISSUE TITLE
Organization edit 'About Us' section

### ISSUE THREAD

**Issue by jadekstewart3** [rubyforgood/pet-rescue#166]
As an organization admin, when I visit "slug/organization_profile/edit".
- On the edit organization page I see an "About Us" field.
- When I enter text into the "About Us" field, and click "Update", I can see that the "About Us" section of my organization has been updated.

[Figma](https://www.figma.com/file/4PqQX8NeOVE9ca2GT4Xz76/Pet-Rescue?type=design&node-id=10-4&mode=design&t=rkMfXskGSM7Tivas-4)

**Comment by LittleBigProgramming** [comment]
Hey :) I would like to work on this if it's available?

**Comment by DreamVenerable** [comment]
Can I take this issue?

**Comment by veezus** [comment]
I'm interested in picking this issue up. Is it still available?

**Comment by nsiwnf** [comment]
Duplicate of #480
