### ISSUE TITLE
Organization edit  'Contact Details' section

### ISSUE THREAD

**Issue by jadekstewart3** [rubyforgood/pet-rescue#167]
As an organization admin, when I visit "slug/organization/edit".
-  I see  "Address", "Phone Number", "City", "Zip Code" fields.
- When I enter text into the any of the above fields, and click "Update", I can see that the contact details section of my organization has been updated.
- If I fail to enter any text and click the "Update", I am shown an error message and redirected to the 'edit organization' page.

[Figma](https://www.figma.com/file/4PqQX8NeOVE9ca2GT4Xz76/Pet-Rescue?type=design&node-id=10-4&mode=design&t=rkMfXskGSM7Tivas-4)

**Comment by kasugaijin** [comment]
Completed.
