### ISSUE TITLE
Display of an Organization's information

### ISSUE THREAD

**Issue by jadekstewart3** [rubyforgood/pet-rescue#171]
When I visit an organization's root page I see in the footer (replacing the default content that is currently in the footer):
- The organization's address
- The organization's phone number

![image](https://github.com/rubyforgood/pet-rescue/assets/95949082/1eb835d9-417c-4dda-ba83-851999b2647a)

**Comment by sean-dickinson** [comment]
@jadekstewart3 I'd be happy to take this one. Just looking into it and I'm wondering what should be shown for an address? It looks like the `Location` model doesn't actually have a street address just a city, state/province, zipcode and country.

**Comment by jmilljr24** [comment]
@sean-dickinson All yours!

>It looks like the `Location` model doesn't actually have a street address just a city, state/province, zipcode and country.

City, state/province, zipcode and country is good. `organization_profile` model has the phone number. Let me know if you have any more questions.
