### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by Eduardo06sp** [rubyforgood/pet-rescue#18]
It doesn't seem that the project has a license, and I think it would be really helpful to choose one early on, especially as contributions get made to the project.

Here is Github's guide: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by thezeeshann** [comment]
@Eduardo06sp assign me this issue. I can add a license file.
