### ISSUE TITLE
Remove extra links in the footer that aren't being used

### ISSUE THREAD

**Issue by edwinthinks** [rubyforgood/pet-rescue#188]
Remove these sections that aren't used anymore

**Screenshot:**
![jam-screenshot](https://cdn-jam-screenshots.jam.dev/0393300b-9ddb-4b12-a1c1-ddf95fa46907.png)

**Full screen:**
![jam-full-url-screenshot](https://cdn-jam-screenshots.jam.dev/c4282b9b-d082-40e9-a909-a4d9fc593b10.png)

\-------------------------------------

**Website URL:**
[http://localhost:3000/](http://localhost:3000/)

**Device and browser info:**
Chrome 117.0.0.0 (1528x946) | Mac OS (arm) 10.15.7

**Date and time:**
September 25th 2023 | 11:09pm UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/076a835b-58da-4778-a08f-a0f4384fe210](https://jam.dev/c/076a835b-58da-4778-a08f-a0f4384fe210)

\-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by Sanyam-jain30** [comment]
Hey, I have expertise in it, can I please be assigned to it?

**Comment by elidakirigo** [comment]
hi, @edwinthinks I can remove the unused links and ensure the page design is still functioning well, can you assign me please?

**Comment by edwinthinks** [comment]
@elidakirigo its yours :)

**Comment by elidakirigo** [comment]
on it :)

**Comment by elidakirigo** [comment]
hi @edwinthinks going through the project I noticed I needed ruby installed in order to proceed with local setup, I haven't worked with ruby hence I would not be fit for this task, sorry feel free to unassign kindly.

**Comment by ErinClaudio** [comment]
@nsiwnf If you want I can take this one. or @kasugaijin
