### ISSUE TITLE
Remove unused top-nav elements that we aren't using yet

### ISSUE THREAD

**Issue by edwinthinks** [rubyforgood/pet-rescue#194]
Remove
- Hamburger Icon
- Search
- The "Dark Mode" icon (can't see the actual icon
- Notification bell
Keep
- The avatar on the top right

**Screenshot:**
![jam-screenshot](https://cdn-jam-screenshots.jam.dev/52a2fc51-9934-4858-9272-9d0056e1eb7f.png)

**Full screen:**
![jam-full-url-screenshot](https://cdn-jam-screenshots.jam.dev/8dc7da1d-8896-49a5-9795-66b953ed754c.png)

\-------------------------------------

**Website URL:**
[http://localhost:3000/alta/dashboard](http://localhost:3000/alta/dashboard)

**Device and browser info:**
Chrome 117.0.0.0 (1335x837) | Mac OS (arm) 10.15.7

**Date and time:**
September 26th 2023 | 11:55am UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/ac1cc45d-c25a-4481-a811-c5594bb4a1c6](https://jam.dev/c/ac1cc45d-c25a-4481-a811-c5594bb4a1c6)

\-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by Vayras** [comment]
@edwinthinks I would like to contribute towards this issue.

**Comment by Yuji3000** [comment]
Would this be as simple as deleting them in the view and updating tests?

**Comment by agiantbird** [comment]
@edwinthinks I would be interested in taking on this little bit of cleanup if it's still available for assignment 🙂

**Comment by edwinthinks** [comment]
@nsiwnf sure we can keep it, I mainly wrote this to clean it up until we got it to work. Fine with removing or if we want to expand scope a bit to make it work.

**Comment by PhantomSean** [comment]
Hey @edwinthinks I'd be happy contribute and take this issue

**Comment by DreamVenerable** [comment]
I'd also like to take this issue if no one does

**Comment by edwinthinks** [comment]
@PhantomSean sorry for the late reply, I can assign it to you.

Sorry @DreamVenerable since @PhantomSean asked first I'll assign them first.

**Comment by DreamVenerable** [comment]
Yes no problem!

**Comment by PhantomSean** [comment]
Thanks @edwinthinks. Just a quick question, is there currently a known issue with the test cases for login/logout failing? Just cloned the repository and ran `rails test:all` and was hit with 3 failures.

**Comment by PhantomSean** [comment]
I think this issue can be marked as closed now that its been merged.
