### ISSUE TITLE
Replace dashboard "brand" with the name of the Current.tenant/organization

### ISSUE THREAD

**Issue by edwinthinks** [rubyforgood/pet-rescue#199]
Replace this non-rendering brand icon with the name of the `Current.tenant` or the name of the organization

**Screenshot:**
![jam-screenshot](https://cdn-jam-screenshots.jam.dev/03aeeeca-1253-49b3-b1b5-6c282eecd423.png)

**Full screen:**
![jam-full-url-screenshot](https://cdn-jam-screenshots.jam.dev/5c9432f2-1018-490c-ae45-9651b67c5992.png)

\-------------------------------------

**Website URL:**
[http://localhost:3000/alta/pets#](http://localhost:3000/alta/pets#)

**Device and browser info:**
Chrome 117.0.0.0 (1335x837) | Mac OS (arm) 10.15.7

**Date and time:**
September 27th 2023 | 12:57am UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/846a6dee-d6dc-48fc-8058-8b48a6d9f9aa](https://jam.dev/c/846a6dee-d6dc-48fc-8058-8b48a6d9f9aa)

\-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by edwinthinks** [comment]
@aileenchoi are you going to still work on this?

**Comment by vinayverghese** [comment]
@kasugaijin This can be closed, I assume?

**Comment by kasugaijin** [comment]
Yes indeed @vinayverghese
