### ISSUE TITLE
Complete your first issue!

### ISSUE THREAD

**Issue by nsiwnf** [rubyforgood/pet-rescue#20]
### What
When an Adopter submits an application for a pet, they see a notice "Application submitted! ..." 

Add a fun message to append to this. Ex.
<img width="358" alt="Screen Shot 2023-07-25 at 7 15 30 PM" src="https://github.com/rubyforgood/pet-rescue/assets/34173394/9c893abb-b1fc-4142-a880-43f520cf9073">

### Why
This is a beginner-friendly change to get started with contributing to pet-rescue.

**Comment by bilalshaikh292** [comment]
heyy @nsiwnf I would like to contribute ?

**Comment by nsiwnf** [comment]
@bilalshaikh292 Great! This issue is not quite ready to be worked on. Give us one more day to do more repo clean-up and prep :)

**Comment by bilalshaikh292** [comment]
Any other issue i could work on

**Comment by rmiller220** [comment]
does this issue still need to be completed?

**Comment by nsiwnf** [comment]
Closing issue - not needed
