### ISSUE TITLE
Update all forms to utilize bootstrap_form so that styling of forms adheres closer to Bootstrap

### ISSUE THREAD

**Issue by edwinthinks** [rubyforgood/pet-rescue#206]
I noticed that we aren't using https://github.com/bootstrap-ruby/bootstrap_form which should make things much easier when building out forms. One thing I noticed for example, was that we needed to add "*" to required fields right now. Whereas if we utilize the specified gem we should have less overhead when developing forms.

Acceptance Criteria
- Install https://github.com/bootstrap-ruby/bootstrap_form
- Replace the forms we have to utilize bootstrap_form syntax
- Update redundant 'labels' caused by switching to use bootstrap_form since bootstrap_form handles those for you.
- Ensure the "*" required asterisk appears when the field is required.

**Comment by reyes-dev** [comment]
I'm interested in working on this issue, may I be assigned?

**Comment by edwinthinks** [comment]
Thanks @reyes-dev. its yours!

**Comment by kasugaijin** [comment]
Glad you found your way here @reyes-dev

**Comment by reyes-dev** [comment]
Thanks for the warm welcome @kasugaijin !
