### ISSUE TITLE
Add breadcrumb support in our  dashboard layout so users can navigate more easily.

### ISSUE THREAD

**Issue by edwinthinks** [rubyforgood/pet-rescue#209]
In order to help users self-locate in our application, we should include breadcrumbs so it is clear where the user is and give options to go back easily.
# Criteria
- Uses the styling provided by the theme https://geeksui.codescandy.com/geeks/docs/breadcrumb.html
- Ideally create a resuable method/helper or whichever approach since we'll be using this in multiple pages.

**Screenshot:**
![jam-screenshot](https://cdn-jam-screenshots.jam.dev/457d533b-fd4b-4cf4-a963-13ffb0911278.png)

**Full screen:**
![jam-full-url-screenshot](https://cdn-jam-screenshots.jam.dev/815ac9cd-2f72-4759-8d81-a54a3cb061ad.png)

\-------------------------------------

**Website URL:**
[http://localhost:3000/alta/dashboard](http://localhost:3000/alta/dashboard)

**Device and browser info:**
Chrome 117.0.0.0 (1158x837) | Mac OS (arm) 10.15.7

**Date and time:**
September 29th 2023 | 10:43am UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/d847f8c6-beaf-4148-ab8e-cf19d86dcf02](https://jam.dev/c/d847f8c6-beaf-4148-ab8e-cf19d86dcf02)

\-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by heyapricot** [comment]
Closed by #231
