### ISSUE TITLE
An organization can edit, update their profile

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#213]
Blocked by: https://github.com/rubyforgood/pet-rescue/issues/216

Enable each organization to edit and update their profile.
Create the necessary db table, model, route, controller and view directory to achieve this.

Acceptance criteria: 
- one can add a new organization profile in the console
- Table organization_profiles has columns: location_id (index), email, phone_number
- Router: only permits one profile per organization (see adopter profile route)
- Model: OrganizationProfile belongs to Organization, Location
- Controller: #edit and #update actions

**Comment by yuricarvalhop** [comment]
Hey @kasugaijin, I could do this one

Some questions: 
Is this name the same that is currently on Organization?
Is there a planning to have multiple profiles per orga? otherwise this fields could be saved directly on the orga..

thanks!

**Comment by kasugaijin** [comment]
Ok great. All yours. 
Good questions. I removed name the table columns required, as that will be on the Organization itself. An organization should have one profile. I think there's long-term benefit to splitting these into separate tables/models as the profile will likely grow a bit more complex. Also, for MVP we are creating Organizations and admin users via the console, and having to input all profile data at this stage would also be a lot more work. I see more pros than cons :)

**Comment by yuricarvalhop** [comment]
@kasugaijin Thanks for the clarifications! 

Some more questions that popped up: 
Is the profile required?
Do we want to go the same approach from adopter profile? (That would mean add a `new` and `create` that can be accessed when the orga has no profile)

In case we dont want the two actions: 
should I add a migration to generate a profile for the existing orgas, or is just adding to the seeds enough?

**Comment by kasugaijin** [comment]
@yuricarvalhop yes every organization should have a profile. I currently have [this PR](https://github.com/rubyforgood/pet-rescue/pull/240) so we can set up an organization via the console (creates organization, user, staff_account and add the admin role to the staff_account). Once your PR is merged, we can add the creation of necessary associations (location, profile) in this console script. 

As for the seeds, I would create the necessary associated objects eg. location and profile. 

Let me know if you want more details.
