### ISSUE TITLE
Add "species" to pet model

### ISSUE THREAD

**Issue by nsiwnf** [rubyforgood/pet-rescue#222]
DB migration to add "species" field to the pet model. Species can be things like "cat", "dog"

**Comment by jadekstewart3** [comment]
I can do this!

**Comment by jadekstewart3** [comment]
@nsiwnf are we including exotic pets like: "rabbit" "rodent" "lizard" "snake"?

**Comment by nsiwnf** [comment]
> @nsiwnf are we including exotic pets like: "rabbit" "rodent" "lizard" "snake"?

Hmm, let's just do "cat" and "dog" for now
