### ISSUE TITLE
Remove location columns on Organizations table and add zipcode to Locations table

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#228]
Currently there is location data stored in the Organizations table `city`, `country`, `zipcode`. This needs to be removed.
Add `zipcode` to Locations table (string). 
Update seed data

Acceptance Criteria:
- seed data loads with errors

**Comment by yuricarvalhop** [comment]
@kasugaijin I can do this one

**Comment by kasugaijin** [comment]
All yours @yuricarvalhop
