### ISSUE TITLE
Revise bootstrap_form field hints and double validation message error

### ISSUE THREAD

**Issue by reyes-dev** [rubyforgood/pet-rescue#244]
Some leftover side effects of adding bootstrap_form to the project from the merge [#221](https://github.com/rubyforgood/pet-rescue/pull/221) that need addressing.

Tasks
- Move hints below labels in  [app/views/devise/registrations/edit.html.erb](https://github.com/rubyforgood/pet-rescue/pull/221/files/4c48a2fc57f5b505e6ccc14538db40cc817eaef3#diff-4d201ae5c67e8b121860359f6c67d044f5bf68c3d7a4687ca64089bfe5677a13)
- Also move the hints below the labels in [app/views/devise/registrations/new.html.erb](https://github.com/rubyforgood/pet-rescue/pull/221/files/4c48a2fc57f5b505e6ccc14538db40cc817eaef3#diff-744d99555c831425cf5883c199055bc537850fbdd075776c69dbad920497bb1f)
- Remove extra asterisk and realign remaining asterisk in [app/views/devise/registrations/new.html.erb](https://github.com/rubyforgood/pet-rescue/pull/221/files/4c48a2fc57f5b505e6ccc14538db40cc817eaef3#diff-744d99555c831425cf5883c199055bc537850fbdd075776c69dbad920497bb1f)
- Remove extra validation in [app/views/organizations/pets/_form.html.erb](https://github.com/rubyforgood/pet-rescue/pull/221/files/4c48a2fc57f5b505e6ccc14538db40cc817eaef3#diff-781e0525ee672f838f528dde170ce64634c5babfc318a22bd530907238b3424c)

**Comment by reyes-dev** [comment]
I would like to handle this issue.

**Comment by kasugaijin** [comment]
All yours! @reyes-dev
