### ISSUE TITLE
Add a Contributions section to the Readme

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#254]
We could benefit from some basic contribution guidelines in our Readme. You can use [this](https://github.com/rubyforgood/human-essentials#contributing-guidelines-) for inspiration, but I think at most we need the first main bullet points and some information on tests i.e., pipeline should run green locally and remotely and tests should be added (most of the time).

Also add instructions on how to attribute someone so they are recognized in the All Contributors section 
I.e., commenting on a PR with the following will attribute multiple people
```
@all-contributors
please add @<username> for <contributions>. 
please add @<username> for <contributions>.
```

**Comment by ShrujanaReddy** [comment]
I would like to work on this.

**Comment by Yuji3000** [comment]
Happy to take this one on
