### ISSUE TITLE
Can org staff define the fields they want to show in the adopter and foster profiles?

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#255]
While there is often a lot of overlap in the kinds of information organizations need to know when reviewing applications for pet foster and adoptions, each is going to have a unique set of questions depending on their needs. 

The adopter/foster profile is essentially their application form for a given organization.
Therefore, it would be good if organizations staff can create/edit/save a list of questions they want to ask, and then have these show as attributes in the adopter/foster profile forms. 

I am not sure if this is possible, and what kinds of solutions exist to solve such a need. This ticket is to investigate the options, if any, to achieve this.

If this is not possible, perhaps we could have a master list of possible questions that staff can choose form, and these are used to create the adopter/foster profile forms. Any new, required questions can be added to this list for all orgs to use if desired.

Ideas welcome.

**Comment by Ptrboro** [comment]
@kasugaijin, I really like the idea of customizable forms for adopter/foster profiles! It’s definitely doable, but creating a user-friendly UI for form builder might be a big challenge. I can handle the backend stuff but I don't have enough experience to do FE.

Have you thought about integrating with Google Forms instead for now? Users build their forms there, copy the link and we embed them on our site. They will have to review the responses in google forms but they can still manage applications in our app. It's not a perfect solution but it's easier and might be a good starting point. What do you think?

<img width="1403" alt="Screenshot 2023-10-12 at 12 03 28" src="https://github.com/rubyforgood/pet-rescue/assets/16762860/63e3afcd-c70e-4326-96ef-9ff24011015b">

**Comment by kasugaijin** [comment]
Hey @Ptrboro 
Thank you for your thoughts on this! I am not sure how this would be built out on the front end, either.
I think the use of Google Forms could work, but we would not be able to build much functionality out of it would we? I mean, unless we can pull all the data to our database, we would not have that data to work with. That would be a limitation. I am more of a fan of keeping the data within our database.

I hit up chatgpt with this and it said:

To create a flexible questionnaire system where each organization can define their own set of questions, you'll need to implement a dynamic form builder. Here's a step-by-step guide on how to approach this in your Rails application:

1. **Models**:

   - Create a `Questionnaire` model that will serve as the main container for questions.

   - Create a `Question` model to represent individual questions. Each question will belong to a questionnaire.

   - Create a model (e.g., `Organization`) to represent the organizations that will create their own questionnaires.

2. **Associations**:

   - Set up associations between `Organization`, `Questionnaire`, and `Question` models. For example, an organization `has_many` questionnaires, a questionnaire `has_many` questions, and a question `belongs_to` a questionnaire.

3. **Attributes**:

   - Allow organizations to define attributes for their questions. For instance, an attribute might be the question's label, type (text, multiple choice, etc.), options (for multiple choice questions), etc. You can use a JSON or serialized column in the `Question` model to store these attributes.

4. **Form Builder**:

   - Create a form builder in your application where organizations can add, edit, and delete questions for their questionnaires.

5. **Rendering the Questionnaire**:

   - When it's time for an adopter to fill out the questionnaire, retrieve the questions associated with the specific organization's questionnaire.

   - Use these questions to dynamically generate the form fields. Depending on the type of question (text, multiple choice, etc.), render the appropriate HTML input.

6. **Storing Answers**:

   - When the adopter submits the form, store their answers in a separate model (e.g., `QuestionnaireResponse`). This model will have a reference to the `Questionnaire`, `Question`, and the adopter who filled out the questionnaire. This could be a single JSON column storing question, answer pairs.
   
For the Dynamic Form builder:
 Retrieve Questions:
In your controller, retrieve all the questions associated with a specific questionnaire.
Generate Form in View:

In your view, loop through the questions and render form fields based on their attributes.
Use the label, type, and options attributes from each question to determine how to render the form field.

Albeit very high level, I think this is a reasonable approach? It does come with tradeoffs of using JSON instead of table columns, but with that comes the flexibility.

**Comment by Ptrboro** [comment]
Hey @kasugaijin! I agree, it would be way better if we could handle all of this on our side. Also easier to manage for organizations because they have everything in one place. 

The solution suggested by ChatGPT looks good as a starting point but is not very flexible. E.g. it does not support grouping questions into sections (as we have now) or adding non-question elements to the form (like description or images).

Keeping the order of questions will also be problematic. Databases don’t naturally keep the order of records, so we will have to handle this somehow ourselves ([and it's not a trivial problem](https://softwareengineering.stackexchange.com/questions/195308/storing-a-re-orderable-list-in-a-database)).

To address these issues we could store the whole form definition as JSON. I think something like this could work:
```
[
  {
    id: 'a79ed395-52ac-4c4b-9c96-b7e6e3e82adb',
    type: 'section',
    properties: {
      title: 'Your personal details',
      subtitle: 'Fill in your details below to get to know you more'
    },
    content: [
      {
        id: '7e157c4f-fd17-49b1-866d-8245eb5310b2',
        type: 'text',
        properties: {
          content: 'Your data will be only used to process your application and will not be shared with any third parties.'
        }
      },
      {
        id: '4a6b1af6-0794-4b4d-9f41-1b9750948c17',
        type: 'text_input',
        properties: {
          title: 'Name',
          placeholder: 'Enter your full name',
          required: true,
          helper_text: 'Please enter your full name'
        }
      },
      {
        id: '8801c067-5dda-4051-8ec8-fff4390fbfdf',
        type: 'phone_input',
        properties: {
          title: 'Phone number',
          placeholder: 'Enter your phone number',
          required: false,
          default_area_code: '+44'
        }
      }
    ]
  }
]
```
(it's inspired by [Notion data model](https://www.notion.so/blog/data-model-behind-notion) but simplified to our needs).
It allows users to define sections and the content of these sections. Each element of the `content` array will be rendered on FE based on the type of the element and its properties.

Pros:
1. you can alter it with plain ruby (vs SQL in the relational model)
2. preserves the order of questions OOTB
3. supports sections
4. supports static elements (like text)
5. is easily extensible

Cons:
1. it is denormalized, meaning we can't enforce constraints on the DB level
2. interacting with it with SQL is harder (e.g. checking how many questions on average do organizations add? Can be done thanks to PG amazing support for JSON but it is harder)

**Comment by kasugaijin** [comment]
Oh interesting @yuricarvalhop thank you for sharing that. I learned something. I think this would be good to discuss at the next team meeting, too. I will admit it's not something I have dealth with before so I would like to hear what others have to say. I do like this suggestion, though, as sections and order would be important to maintain. With this kind of approach for this kind of feature, I think there will always be trade offs, so I can canvas the team for input. I can make a slack discussion on it.

**Comment by kasugaijin** [comment]
There was already a decided upon approach from the Ruby for Good conference, where a dynamic form builder would be made possible following a similar architecture to the checklists. Per this discussion (may not be accessible to all): https://rubyforgood.slack.com/archives/C05JB50LEN5/p1697309378963579

The analogous checkilist models are:
```
Questionaire -> ChecklistTemplate
Questions -> ChecklistItems
QuestionResponse -> ChecklistAssignment
```

In simple terms, a questionnaire is the template, a question is an item that belongs to a template, and a response belongs to an item. Questions will enable different form input types, and we use a dynamic form builder to render the appropriate form.
