### ISSUE TITLE
As staff, I want to be able to see the applications for a pet from the pet info page

### ISSUE THREAD

**Issue by nsiwnf** [rubyforgood/pet-rescue#258]
As staff, when I click the "Applications" tab, I should see a list of applications open for this pet (where "Summary is for "Overview")

<img width="786" alt="Screen Shot 2023-10-10 at 6 16 43 PM" src="https://github.com/rubyforgood/pet-rescue/assets/34173394/29c7846b-2116-4110-82f6-b829788d77ba">

**Comment by aisayo** [comment]
Hi, I would like to work on this. Can you please assign to me

**Comment by kasugaijin** [comment]
All yours! @aisayo 
Note that @ErinClaudio working on https://github.com/rubyforgood/pet-rescue/issues/257 has an approach to use to render the required template when clicking the Applications tab. Would be good if we're consitent.

**Comment by kasugaijin** [comment]
FYI this PR is a pre-cursor for setting up nice partials and will set the approach for this ticket.
https://github.com/rubyforgood/pet-rescue/pull/265

**Comment by aisayo** [comment]
Hello @kasugaijin , should tests be written as well?

**Comment by nsiwnf** [comment]
@aisayo @kasugaijin  Yes, I think so! Take a look at https://github.com/rubyforgood/pet-rescue/pull/275 for an example if needed

**Comment by kasugaijin** [comment]
@aisayo please follow the use of nice partial gem and routes like Staff-can-view-checklist-on-pets-show-and-interact
