### ISSUE TITLE
Redirect New Staff to Dashboard After Setting Password from Invitation Link

### ISSUE THREAD

**Issue by marlena-b** [rubyforgood/pet-rescue#264]
When a new staff accepts the invitation and sets the password the redirect now goes to the root url. We want to redirect to the dashboard.

**Comment by Ptrboro** [comment]
I think this is blocked by https://github.com/rubyforgood/pet-rescue/issues/278

**Comment by queen-x-vee** [comment]
hello, may I work on this pls

**Comment by Ptrboro** [comment]
Hey @queen-x-vee! I'm afraid this issue is waiting on a fix for https://github.com/rubyforgood/pet-rescue/issues/278. I'm on it today and will ping you once it's sorted. I've already assigned this ticket to you. Hang tight and thanks for your help!

**Comment by Ptrboro** [comment]
@queen-x-vee my PR is waiting for review: https://github.com/rubyforgood/pet-rescue/pull/346 :)

I also noticed that the layout for staff index is currently broken and the button to invite new staff is missing. I will add an issue to fix it but right now you can access the invitation form view by opening the link: http://127.0.0.1:3000/alta/users/invitation/new

**Comment by kasugaijin** [comment]
This issue is good to go now right @Ptrboro ?

**Comment by Ptrboro** [comment]
@kasugaijin it is! :) The problem with broken links in mailers was fixed. Sorry for the late reply.

**Comment by Tomaszabc** [comment]
I would like to help with this task. Can I be assigned ?

**Comment by Ptrboro** [comment]
@Tomaszabc Sure thing, reassigning it to you!

**Comment by Tomaszabc** [comment]
Thank You
