### ISSUE TITLE
Staff can upload a profile pic

### ISSUE THREAD

**Issue by nsiwnf** [rubyforgood/pet-rescue#268]
As staff, I can upload an avatar image
As staff, I can see my image in the log out/settings menu at the top right corner

As admin, I can see staff's images in the "Staff" index page 

Include a default image if staff has not uploaded an image

**Comment by yuricarvalhop** [comment]
@nsiwnf can I work on this one?

**Comment by yuricarvalhop** [comment]
@nsiwnf should Its worth it to move this logic into a concern, or you dont think we are gonna need this logic somewhere else?

**Comment by nsiwnf** [comment]
Good question - we might want it for `adopters` as well so a concern would be a good approach!
