### ISSUE TITLE
Staff can pause pet applications

### ISSUE THREAD

**Issue by nsiwnf** [rubyforgood/pet-rescue#272]
As staff, I can pause/unpause applications from the pets index screen 

Mock:
<img width="1164" alt="Screen Shot 2023-10-14 at 11 26 39 AM" src="https://github.com/rubyforgood/pet-rescue/assets/34173394/007a0a00-402e-4b6a-a922-307a57feb652">

**Comment by Ptrboro** [comment]
Hey @nsiwnf, I think this can already be done, the option is just hidden in the dropdown. Do you want to pull this out of the dropdown and put it directly as a column instead?

<img width="1208" alt="Screenshot 2023-10-15 at 16 34 25" src="https://github.com/rubyforgood/pet-rescue/assets/16762860/a798d02e-7847-410d-aef6-eef6d843ef87">

**Comment by nsiwnf** [comment]
@Ptrboro Right, I think it would be better to move that out of the menu into a column. Currently the "pause applications" in the menu doesn't include a "pause_reason"

**Comment by kasugaijin** [comment]
I was debating whether we need a pause reason column any more. I am inclined to get rid of it. It made sense for one org with specific reasons, but now I think for many orgs just a simple pause feature works fine.

**Comment by nsiwnf** [comment]
Ok great - either way, I think a toggle "pause application" column on the index page would be good, right?

**Comment by kasugaijin** [comment]
Yes I agree @nsiwnf

**Comment by aisayo** [comment]
Hello, I would like to work on this. 

I have a couple questions:

1. I noticed the button redirects to the pets show page after the status of the application has been clicked. Do you want to maintain that behavior? I was thinking of updating the DOM dynamically for a better user experience. 
2. Is there a way to add custom css if necessary? I noticed in the photo provided, the toggle button has text content rendered from within the switch. I don't know that this is doable by just using bootstrap

**Comment by nsiwnf** [comment]
@aisayo Great!
> 1. I noticed the button redirects to the pets show page after the status of the application has been clicked. Do you want to maintain that behavior? I was thinking of updating the DOM dynamically for a better user experience.

Agreed - we dont need to redirect to the "show" page

> 2. Is there a way to add custom css if necessary? I noticed in the photo provided, the toggle button has text content rendered from within the switch. I don't know that this is doable by just using bootstrap


Hm, I think we're trying to avoid custom css - go ahead and leave out the text or make any other changes that are supported by bootstrap/geeksui

**Comment by kasugaijin** [comment]
@aisayo how's this one going?

**Comment by jmilljr24** [comment]
Can I be assigned to this?
