### ISSUE TITLE
Add status to pets table

### ISSUE THREAD

**Issue by jadekstewart3** [rubyforgood/pet-rescue#282]
Create a migration that will add a status to the pets table that allows the designation of the pets status "adoptable", "fosterable", or "adoptable and fosterable".

Completion Criteria:
- [ ] As an organization member, when I visit "/organization/pets/:id/edit" I see a field on that form to edit the status of the pet. After I change and update the status of a pet, when I visit "/organization/pets/:id", I can see the pets updated status displayed in the summary card.

**Comment by reyes-dev** [comment]
I would like to be assigned this issue. A few quick questions, in case I get assigned:

1. I don't see an adoptable_pets table in the schema, do you mean the pets table?
2. Should the new column be named "status" or something like "adoptable_status"?

**Comment by jadekstewart3** [comment]
@reyes-dev Hi! You're right. It should be on the pets table! Sorry about the confusion, I'll fix the ticket itself. I was originally thinking just status, but erring on the side of specificity makes sense also! 
@kasugaijin @edwinthinks @nsiwnf Do any of you have strong opinions on the title of this row?

**Comment by kasugaijin** [comment]
I get where you're going with status but it is quite generic. I wonder if something like `availability` or `placement_type` or `adoptable_fosterable`. Ideally one could look at the column name and have a good chance of guessing what it's for.

**Comment by jadekstewart3** [comment]
@reyes-dev Are you still working on this?

**Comment by reyes-dev** [comment]
@jadekstewart3 I wasn't assigned so I haven't done any work on it.

**Comment by jadekstewart3** [comment]
@reyes-dev oh! do you still want to work on it? I can assign you right now
