### ISSUE TITLE
Organization Dashboard

### ISSUE THREAD

**Issue by jadekstewart3** [rubyforgood/pet-rescue#284]
We need to set up a route that points to a show action in the Organizations Dashboard controller.

Completion Criteria:
- [x] Route that points to a index action in the organization dashboard controller
- [x] index action in the organization dashboard controller
- [x] Organization dashboard utilizes [this geeks ui layout](https://geeksui.codescandy.com/geeks/pages/profile-edit.html)
- [x] Displays organization name

**Comment by kasugaijin** [comment]
Some clarification for the UI markup, I think we'd want to use this component within our existing admin dashboard template
<img width="969" alt="image" src="https://github.com/rubyforgood/pet-rescue/assets/95949082/2de79d37-d8ad-4272-984f-3140a7144dc5">
