### ISSUE TITLE
Remove defaults from columns with foreign keys

### ISSUE THREAD

**Issue by Ptrboro** [rubyforgood/pet-rescue#297]
Default values on foreign keys can lead to hard to find bugs like the one here: https://github.com/rubyforgood/pet-rescue/pull/296#discussion_r1367905909. I suggest dropping these defaults so we don't miss similar issues in the future.

Default values should be removed from these columns:

- [ ] `adopter_accounts.user_id`, 
- [ ] `staff_accounts.organization_id`, 
- [ ] `staff_account.user_id`

@kasugaijin, @edwinthinks are you ok with this?

**Comment by kasugaijin** [comment]
@Ptrboro yes this makes sense to me.
