### ISSUE TITLE
Improve and fix pets search

### ISSUE THREAD

**Issue by Ptrboro** [rubyforgood/pet-rescue#303]
The search on the pets list is broken now, let's fix and improve it:

<img width="941" alt="Screenshot 2023-10-26 at 18 56 05" src="https://github.com/rubyforgood/pet-rescue/assets/16762860/de8df388-744d-4777-8b66-8fead5bb5481">

As staff, I should be able to search the pets list by:
- name (text field, matches partially, case insensitive, so e.g. filtering by "uc" should return pet called "Lucy")
- species (select field - use values from `Pet.species` enum)
- sex (select field - male / female)
- adoption status (select field - adopted / seeking adoption)

There should be a single submit button (we can call it "Search").

I recommend using the [ransack gem](https://github.com/activerecord-hackery/ransack), but plain ruby implementation is also great :)

**Comment by Ptrboro** [comment]
@kasugaijin I'd like to hear what you think about this. Should we add some more filters?

**Comment by kasugaijin** [comment]
@Ptrboro yes this is something that needs working on thank you for making the issue. I would also add a filter for Pet species per https://github.com/rubyforgood/pet-rescue/issues/304
