### ISSUE TITLE
Allow to set species on pet create/edit form

### ISSUE THREAD

**Issue by Ptrboro** [rubyforgood/pet-rescue#304]
As a staff, I should be able to set the species of the pet when I'm creating/editing it.

Acceptance criteria:
1. add species select with values from the species enum in Pet model (you can access them with `Pet.species.keys`) 
2. the select should be after Sex and before Breed field
3. species should be saved on pet after submitting the form

<img width="549" alt="Screenshot 2023-10-26 at 19 18 47" src="https://github.com/rubyforgood/pet-rescue/assets/16762860/7db3dc25-7753-42c6-918f-461ae7b61742">

note: the form is broken now, adding this field should fix it :)

**Comment by MooseCowBear** [comment]
I can work on this. Species should be a required field like the others?

**Comment by kasugaijin** [comment]
@MooseCowBear all yours
Yes it is a required field.
