### ISSUE TITLE
As staff or admin I should be redirected to /pets index after logging in

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#305]
Currently after log-in staff are redirected to /baja/dashboard
This should be changed to /pets index view.

Acceptance criteria
- staff are redirected to /pets after log in
- test

**Comment by jp524** [comment]
I'd like to help with this issue!

**Comment by kasugaijin** [comment]
@jp524 all yours

**Comment by edwinthinks** [comment]
@kasugaijin would it make sense actually to go to dashboard instead once it is built out? I think for the interim doing this change makes sense.

**Comment by kasugaijin** [comment]
@edwinthinks yes I agree once we have a dashboard built out the redirect would go there.
