### ISSUE TITLE
As staff I can click Organization in the sidenav and see the show page for organization profile

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#306]
`/dashboard` routes to dashboards controller #index action and renders the associated template. This template is actually the one we want to use for the organization profile show and edit pages. So we need to move this template to views > organization profile and also make the show and edit template use the same HTML/layout. Add the actual fields for the Organization profile to this layout and keep the other fields (disabled) as empty placeholders for now. 

Then, change the 'Settings' link in the side navbar to 'Organization' that links to the show organization profile path.

There should be an Edit button on the show page, that takes the user to the Edit form, where they can save and are redirected back to the show page with a flash notice the profile was update.

**Comment by edwinthinks** [comment]
I can take this and also start building out tiny bits of the dashboard.

**Comment by kasugaijin** [comment]
@edwinthinks great!
