### ISSUE TITLE
As staff I can view adopter applications for a given pet via the /pet/:id Applications tab

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#307]
Currently, all applications are viewable at `/adoption_application_reviews`
We want to also see the applications for a specific pet on that pet's show page under the Applications tab

Acceptance criteria
- a pet's adopter applications are shown on /pet/:id Applications tab
- follows implementation to render tab partials used for checklists ([PR](https://github.com/rubyforgood/pet-rescue/pull/265) still in progress)

**Comment by MooseCowBear** [comment]
I'd like to take a stab at this.

**Comment by MooseCowBear** [comment]
2 quick questions...

It looks like as of now there's no application partial, so my thought is to move the current application rendering that appears in adoption_application_reviews/index.html.erb into a partial that can be shared by both that view and the applications tab partial for the pet show view. Is it okay to go ahead and do that and then update the adoption_application_reviews/index.html.erb accordingly?

Second, it looks like the controller action for the tabs is going to be taken care of in pull #265 and that this line in the pets show view will render the partial for the selected tab:

![Screenshot_2023-11-07_at_7 05 49 AM](https://github.com/rubyforgood/pet-rescue/assets/82609260/55a8aefb-5d88-4244-b72a-cdcc9f825b59)

Does this mean I should add the tab partial for the pet's applications in the organizations/tasks directory?

**Comment by MooseCowBear** [comment]
As of now, I've created the shared partial. It leaves the layout of adoption applications reviews index unchanged. For the applications tab on the show page, I could see the partial rendered in a card like: 

<img width="973" alt="Screenshot 2023-11-10 at 12 14 46 PM" src="https://github.com/rubyforgood/pet-rescue/assets/82609260/c4bc6178-9d16-4a21-b9ed-6f2b2f153c9b">

Or without the header: 

<img width="986" alt="Screenshot 2023-11-10 at 12 14 30 PM" src="https://github.com/rubyforgood/pet-rescue/assets/82609260/69baef7c-72d2-4543-8c60-f9497201e2ac">

Either way, that's what it would look like if dropped into the tasks/applications.html.erb file of pull #265. Since that pull hasn't been merged yet, I could put the card in its own partial file? Or hold off until that pull has been merged? Let me know.

**Comment by kasugaijin** [comment]
Great! I think there's nothing to stop you carring on here. If yours is merged first, then @ErinClaudio can just accept the incoming on a conflict to overwrite his current file. 

If you want to continue working on this in this PR, you could fix up the _applications partial and render each application in a table like we use for the staff index or pets index table. So we would have an Applicant column, Status Column and links or buttons to view adopter profile, edit application or create an adoption. Does that make sense?

**Comment by MooseCowBear** [comment]
Yes, makes sense. I'll start working on that.

**Comment by MooseCowBear** [comment]
Ok so let me know what you think of this. This would be how the partial would render on the adoption applications reviews index page: 

<img width="954" alt="Screenshot 2023-11-11 at 8 14 57 AM" src="https://github.com/rubyforgood/pet-rescue/assets/82609260/a396ffee-4958-49c7-9922-cf03a8214f50">

And on the pet show applications tab, it would be rendered like: 

<img width="880" alt="Screenshot 2023-11-11 at 7 43 29 AM" src="https://github.com/rubyforgood/pet-rescue/assets/82609260/427ab5bb-998c-42f1-bb4a-833b11c11107">

I kept the conditional rendering of the adopter profile and create adoption links from how it was before. But changed the status to a badge to be consistent with the pet index table, replacing the bolded withdrawn status with a different background color. Obviously doesn't have to be yellow. Could also do different colors for the different statuses.

**Comment by kasugaijin** [comment]
@MooseCowBear Great! I think the table looks cleaner. I am open to ideas (I am no designer), but have some ideas:

Column Order
- related things are better next to each other, so let's put the Adopter Profile column second, next to Applicant column. I think we could just rename the Adopter Profile column to just Profile. Then have the Edit Application column third, renamed to just Edit, followed by Status and finally Confirm Adoption (renamed from Create Adoption).

Status column
- I think we can get rid of 'status:' text in each row and just show the status value
- Some ideas on colours: we can either make them all the same colour for now and revisit colours later when we have UX support, or if you feel like making some colours depending on status, can do something like:
- Withdrawn could be black text on light grey background
- Successful Applicant and Adoption Made could be black text on pale green background
- Adoption Pending can be black text on pale yellow background
- Under review can be the (current) white text on blue background
- Awaiting review can be white text on darker purple background

The rest of the columns
- What do you think about using an icon in each instead of the current text or button? E.g.:
- Profile column we use `fe-file-text` class icon
- Edit column we use `fe-edit` class icon
- Confirm Adoption we use something like `fe-plus`

**Comment by MooseCowBear** [comment]
All that sounds good. I can go ahead and make the changes in this PR. 

One question: Right now, displaying the applicant's name creates an n+1 problem for the applications review index page. Do you want me to adjust the Pet.org_pets_with_apps method that the applications reviews controller index method uses to take care of this while I'm at it?

**Comment by kasugaijin** [comment]
> All that sounds good. I can go ahead and make the changes in this PR.
> 
> One question: Right now, displaying the applicant's name creates an n+1 problem for the applications review index page. Do you want me to adjust the Pet.org_pets_with_apps method that the applications reviews controller index method uses to take care of this while I'm at it?

Good catch. You can eager load the associated data with `includes` on the initial query.
Also, for future ref, it might be easier to create a draft PR and continue the discussion on there because then reviewers can see any code changes to date, and it's easier to review conversations on the PR (the issue is not the first place to look).
