### ISSUE TITLE
As staff user my edit user settings form is rendered in the dashboard layout

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#308]
The devise form for edit user settings should be rendered within the dashboard layout if the user has an associated StaffAccount.

**Comment by MooseCowBear** [comment]
Is this the idea of what you're looking for?

![Screenshot_2023-10-29_at_7 57 48 AM](https://github.com/rubyforgood/pet-rescue/assets/82609260/66ee0083-f619-4dcc-89c1-91ab23c004e9)

**Comment by kasugaijin** [comment]
Apologies I should have provided more detail here. The link to account settings should remain in the top right avatar, but the form to edit should render within the dashboard layout. Does that make sense? No links need to be added to the dashboard sidenav.

**Comment by MooseCowBear** [comment]
Oh I see. That makes far more sense.

**Comment by kasugaijin** [comment]
PR up: https://github.com/rubyforgood/pet-rescue/pull/319
