### ISSUE TITLE
Give pet status column more contrast in the pets index table

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#325]
The status column shows if pets are active or inactive for adoption/fostering. It is currently hard to read the white text on that colour background.

![image](https://github.com/rubyforgood/pet-rescue/assets/95949082/f9b4634c-046a-4ace-90a3-74677367b56b)

Acceptance criteria
- change the background colour to something with more contrast for the white text eg. Gray 700 here: https://geeksui.codescandy.com/geeks/docs/colors.html

**Comment by MooseCowBear** [comment]
I can do this.

**Comment by MooseCowBear** [comment]
This is unrelated to issue #325, but while I was working on it I noticed there is kind of an awkward margin happening in the dashboard layout, highlighted in this screenshot.

<img width="1312" alt="large_screen" src="https://github.com/rubyforgood/pet-rescue/assets/82609260/05b4fef3-f8c5-4695-947e-2ce393752893">

I found the source of the margin and with a minor change that doesn't appear to affect any functionality could remove it, as in: 

<img width="1310" alt="large_screen_with_change" src="https://github.com/rubyforgood/pet-rescue/assets/82609260/bc68d7c1-26b1-4929-8c87-b3612da93923">

This does affect the mobile view slightly, but not in an objectionable way. 

Before the change:

<img width="706" alt="small_screen" src="https://github.com/rubyforgood/pet-rescue/assets/82609260/9e338771-046b-4c5e-a25e-e90c7c4b12be">

And after: 

<img width="635" alt="small_screen_with_change" src="https://github.com/rubyforgood/pet-rescue/assets/82609260/fc63aab1-7999-48e1-aaaf-57483a087507">

Is this change something you would be interested in? 

Sorry if this is not the right place to bring this up.

**Comment by kasugaijin** [comment]
@MooseCowBear yes this is something that needed a fix :) it was apparently happening on some machines and not others. Could you make a separate PR for that UI change? That would be great.

**Comment by MooseCowBear** [comment]
Will do.
