### ISSUE TITLE
Update the Organization Profile UI to use Geek Theme for profile

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#328]
The template renedered for `/organization_profile/edit` should use the Geeks theme for the profile: https://geeksui.codescandy.com/geeks/pages/profile-edit.html

We should keep the avatar section (although not yet possible to upload on the OrganizationProfile model it can quickly be added with the  avatarable concern)

![image](https://github.com/rubyforgood/pet-rescue/assets/95949082/9950b532-1958-4aef-8507-6e1a9d84e415)

Acceptance criteria
- organization profile edit form uses the geeks layout provided above

**Comment by queen-x-vee** [comment]
may I work on this pls

**Comment by jadekstewart3** [comment]
@queen-x-vee Hi! I've almost finished this issue 😅 Let me know if you find another that you would like to take a crack at!

**Comment by queen-x-vee** [comment]
seen one #332 @jadekstewart3 . can I work on this?

**Comment by kasugaijin** [comment]
@queen-x-vee see my comment on that ticket!
