### ISSUE TITLE
Add avatar partial so we can use it where we need an avatar

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#332]
~~When a user visits `/staff` they see an avatar that is the user's uploaded image or name initials if no image has been uploaded.~~

~~See this PR for implementation: https://github.com/rubyforgood/pet-rescue/pull/326~~

This PR: https://github.com/rubyforgood/pet-rescue/pull/326 implemented a reusable view for avatars but it used view component (which we decided is not a library we want to incorporate at this time) so was reverted. We need the same outcome but using nice_partials instead. 

Acceptance criteria
- use nice partials to create avatar partial that can be used anywhere we need it on the site
- If no uploaded avatar image, use user's name, or organization, initials, otherwise uses uploaded image

**Comment by queen-x-vee** [comment]
Hi, can I work on this please?

**Comment by kasugaijin** [comment]
@queen-x-vee Yes sounds good. I updated the ticket as we need a foundational piece of work for this ticket. So let me know if you are happy to implement this.

**Comment by queen-x-vee** [comment]
Sure! I am.

**Comment by kasugaijin** [comment]
@queen-x-vee all yours!

**Comment by kasugaijin** [comment]
How is this going @queen-x-vee ?

**Comment by kasugaijin** [comment]
@queen-x-vee How's this going? Let me know if you don't want it and I will reassign!

**Comment by kasugaijin** [comment]
Ok this issue is now up for grabs!
FYI @queen-x-vee

**Comment by phonghpham** [comment]
@kasugaijin, I can take this on.

**Comment by kasugaijin** [comment]
Ok all yours @phonghpham
