### ISSUE TITLE
Fix Dashboard Layout

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#336]
This PR https://github.com/rubyforgood/pet-rescue/pull/331 was an attempted fix. It did work for the contributor and for me on my machine, however it now breaks the UI on other machines - see image in this PR https://github.com/rubyforgood/pet-rescue/pull/335. 

This issue is to investigate why this is occurring and find a fix for all.

**Comment by MooseCowBear** [comment]
Now the dashboard layout is also broken for me. But if I revert the change I made in #331, the dashboard now appears as it should (locally at least) and without the large margin that led me to suggest the change in the first place. Not sure why.

**Comment by kasugaijin** [comment]
> Now the dashboard layout is also broken for me. But if I revert the change I made in #331, the dashboard now appears as it should (locally at least) and without the large margin that led me to suggest the change in the first place. Not sure why.

Yes that is strange. I am not yet sure why that is happening. But If your 'fix' is no longer a 'fix' perhaps better to revert and keep an eye on any future issues with the layout.

**Comment by MooseCowBear** [comment]
Exactly what I was thinking.
