### ISSUE TITLE
Use `components/dashboard/page` component in account settings and staff pages

### ISSUE THREAD

**Issue by Ptrboro** [rubyforgood/pet-rescue#347]
You can find more details on the new approach to rendering admin pages here: https://github.com/rubyforgood/pet-rescue/pull/333

These three views are now broken and must be changed to use the new component:
`app/views/devise/registrations/edit.html.erb`
`app/views/organizations/invitations/new.html.erb`
`app/views/organizations/staff/index.html.erb`

**Comment by MooseCowBear** [comment]
I can work on this.

**Comment by kasugaijin** [comment]
@MooseCowBear all yours
