### ISSUE TITLE
Update the form in the sign-up for adopters to use a dropdown for Countries & States.

### ISSUE THREAD

**Issue by edwinthinks** [rubyforgood/pet-rescue#35]
http://0.0.0.0:3000/adopter_profile/new

![Image](https://github.com/rubyforgood/pet-rescue/assets/34173394/ecaf32da-6780-4875-afc5-bc87b3a3197c)

**Comment by ErinClaudio** [comment]
@edwinthinks I can take this one if you would like

**Comment by nsiwnf** [comment]
Completed with #136
