### ISSUE TITLE
As staff I can create a pet in draft so it is not visible to foster/adopters 

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#350]
EDIT: This [PR](https://github.com/rubyforgood/pet-rescue/pull/358) is mostly done! Thank you to @heyapricot for getting it thus far. It just needs to cross the finish line...I think it's just some tests left to go. Anyone want to pick it up? 

Right now, when staff create a pet, it is automatically visible on the pets available for adoption page that fosters and adopters see. We want to change this so staff can create a pet in draft mode so the pet exists in the database, but is not visible to potential adopters, but is visible to staff via the dashboard.

Acceptance criteria
- new column on pets table, called `is_published`, data type `boolean`, `default: false`
- validation on model, required true
- pet new/edit form has a toggle between `draft` and `published` next to, and similar to, the toggle for `applications paused`
- the pet's index table clearly shows when a pet is `published` or `draft` and staff can also toggle the pet between draft and publish via the pets index table, similar to the toggle for `applications paused`
- pet show page summary table displays the value for is_published as Published: 
- update tests for creating/editing a pet and add tests validating that draft pets do not show on the page of adoptable dogs that adopters and fosters see.

**Comment by kasugaijin** [comment]
@heyapricot how's this one going? Hit us up in Slack if you have any questions :)

**Comment by mononoken** [comment]
I would be interested in picking up what is left.

**Comment by kasugaijin** [comment]
Sound good. Thank you @mononoken
