### ISSUE TITLE
Improve look of pet > show > photos table and enable staff to download the photo on click

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#351]
The table of uploaded pet photos is a bit ugly and could do with improving. Also, staff should be able to click the photo (image or filename) to download it.

Acceptance criteria
- the table of uploaded pet photos uses the best selling courses table at the bottom of this page (columns should be Image, filename, then an empty column to hold the delete button): https://geeksui.codescandy.com/geeks/pages/dashboard-instructor.html
- staff can click image or filename in the table and it downloads the photo.

**Comment by diegolinhares** [comment]
Hi @kasugaijin,

Can I get this one?

**Comment by kasugaijin** [comment]
For sure! @diegolinhares

**Comment by diegolinhares** [comment]
Some questions @kasugaijin:

Are we going to remove the columns Name, Sex, Breed, Weight and Status, right? The columns now are going to be Image, Filename and a blank one for the "delete" button.

Are we removing the other options when clicking on the "action" icon and replacing it with a button that represents the action of delete?
