### ISSUE TITLE
As a staff I can filter adopter applications by pet name, applicant name, application status

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#355]
Look at the filter used on the Pet Index page for an idea how to handle it and how it should function and look. 

Acceptance criteria
- staff can filter adopter applications by pet name, applicant name, application status

**Comment by phonghpham** [comment]
@kasugaijin, I'm down for the cause. Please assign this to me!

**Comment by kasugaijin** [comment]
All yours @phonghpham
