### ISSUE TITLE
Clicking on "My Profile" as seed user b@c causes a 500 error

### ISSUE THREAD

**Issue by edwinthinks** [rubyforgood/pet-rescue#36]
https://jam.dev/c/fa8cd7fb-fd12-4408-b470-d6c1f8ca3966

**Comment by Eduardo06sp** [comment]
This has changed per #29 and I am unable to replicate it with the credentials that replaced `b@c`
```rb
email: `adopter1@example.com`
password: `123456`
```

Are you still experiencing the same issue?

**Comment by Thrillberg** [comment]
Closing this because I think it's resolved.
