### ISSUE TITLE
Fix validations in the pet form

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#368]
The pet form does not show validations as it should when data are not valid or missing. There are HTML validations in use, but we also need active record validations that bootstrap form then turns into error messages that display under the input field.

This PR did fix it, but something got broken in the meantime: https://github.com/rubyforgood/pet-rescue/pull/260

Acceptance criteria:
- use bootstrap form validations
- errors show in red under the corresponding input field like the image below

![image](https://github.com/rubyforgood/pet-rescue/assets/95949082/e4fa2baf-1c60-4c1b-a37f-7b811d056f22)

**Comment by diegolinhares** [comment]
Can I get this one?

**Comment by diegolinhares** [comment]
Here the validations are working as you can see:

<img width="509" alt="errors" src="https://github.com/rubyforgood/pet-rescue/assets/3309779/1ba71dde-8f90-44c3-946b-a34020d79a5b">

**Comment by kasugaijin** [comment]
Hey @diegolinhares sure! Yes they work in the org settings form but not in the pet create/edit form.

**Comment by kasugaijin** [comment]
@diegolinhares how's this going? Do you still want to take it on?

**Comment by atbalaji** [comment]
Hi @diegolinhares , in case of reassigning the issue if it is available, I would love to work on this issue. Done some preliminary investigations. Would be happy to help 👍

**Comment by kasugaijin** [comment]
@diegolinhares let me know if you want to keep this or I'll reassign to @atbalaji in a couple days if I don't hear back. Thanks.

**Comment by kasugaijin** [comment]
@atbalaji all yours!

**Comment by kasugaijin** [comment]
I will close this as the validations are working fine in the pet form!

**Comment by atbalaji** [comment]
Hi @kasugaijin , I have a doubt. On testing locally, **pets/new** was fine with active records validations being displayed under the form field. But **pets/edi**t was not displaying the errors due to the `after_action: set_reason_paused_to_none, only [:update]`  in **PetsController**. Was this taken care of ? Would love to know .

**Comment by kasugaijin** [comment]
@atbalaji oh good find. It had beena while since I created and today I noted create form was working fine but did not test update. Feel free to make a PR if you have found an issue and a fix!

**Comment by kasugaijin** [comment]
Note that #387 is a new issue that might take care of this also. It is to remove the pause reason column and associated logic.

**Comment by atbalaji** [comment]
Yeah fix for #387 will take care of this issue too. Cool  @kasugaijin , happy to contribute in case of new issues👍.

**Comment by kasugaijin** [comment]
@atbalaji should be more issues opening up in the next couple of days!
