### ISSUE TITLE
Checkboxes to toggle `completed` on pet tasks

### ISSUE THREAD

**Issue by Thrillberg** [rubyforgood/pet-rescue#386]
Following up on https://github.com/rubyforgood/pet-rescue/pull/384 we want to create `completed` checkboxes for pet tasks that users can check or uncheck directly on the page (ie, no dedicated edit screen or modal). All tasks start with `completed` as `false`.

**Comment by DreamVenerable** [comment]
May I take this?

**Comment by Thrillberg** [comment]
@DreamVenerable Sure thing! Let me know if you have questions or need help!

**Comment by DreamVenerable** [comment]
Alright, thanks!

**Comment by DreamVenerable** [comment]
@Thrillberg How would you like it to look like, a simple checkbox or a toggle just like here #375?

**Comment by Thrillberg** [comment]
Ooh the toggle looks nice to me!

**Comment by edwinthinks** [comment]
Hmm I personally think checkbox because I think its more what people are accustomed to seeing in task lists? What do you both think @Thrillberg @DreamVenerable ?

**Comment by DreamVenerable** [comment]
> I think its more what people are accustomed to seeing in task lists?

I think so too

**Comment by Thrillberg** [comment]
Oh very good point! Let's do checkboxes.
