### ISSUE TITLE
Remove pause reason attribute on Pet 

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#387]
` t.integer "pause_reason", default: 0` is no longer needed.

Acceptance Criteria: 
- migration that removes this column on the pets table 
- remove any code that refers to this column. Ask in Slack if unsure what to do with a specific bit of code.
- tests pass

**Comment by jmilljr24** [comment]
I'd like to work on this.

**Comment by kasugaijin** [comment]
All yours @jmilljr24
