### ISSUE TITLE
Remove strong_migrations Gem from the project

### ISSUE THREAD

**Issue by Ptrboro** [rubyforgood/pet-rescue#391]
We're removing the `strong_migrations` Gem since we don't have a production environment yet and it is only slowing us down. 

Tip: don't forget to remove any `safety_assured` usage in migrations.

**Comment by MooseCowBear** [comment]
I can do this

**Comment by Ptrboro** [comment]
Happy coding @MooseCowBear!

**Comment by edwinthinks** [comment]
@Ptrboro i agree we don't have production yet so it isn't that valueable today. Will we know to reintroduce it later once we do go into production? I guess my thinking was I would keep just using `safety_assured` to just run migrations.

I don't have a strong opinion here so happy to go either way. If we had production, that would be a different story :)

**Comment by Ptrboro** [comment]
@edwinthinks we will probably forget and add it once we break something on prod for the first time 😂 But we already had multiple cases where this caused confusion for newcomers and slowed people down.

I will add a comment in https://github.com/rubyforgood/pet-rescue/issues/54 to increase our chances of not forgetting to reenable it :)
