### ISSUE TITLE
Staff can CRUD Default Pet Tasks

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#395]
As a staff I can CRUD default pet tasks.

Acceptance criteria
- uses the same implementation as the Pet > Tasks tab to CRUD a new task (UI and Turbo Stream)
- I can create, update, edit a default pet task

**Comment by vmyts539** [comment]
May I?

**Comment by kasugaijin** [comment]
All yours @vmyts539
