### ISSUE TITLE
As Staff I can add a 'due date' on a pet task

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#402]
**Update:** PR https://github.com/rubyforgood/pet-rescue/pull/409 for this task is almost complete, someone just needs to take it past the finish line :) Please ensure designs adhere to Tasks V2 here [FIGMA](https://www.figma.com/file/0jVgYASUJy0KiX3BVc3dFM/Tasks?type=design&node-id=0-1&mode=design&t=wqtzgNOthljYf2fy-0) (just focusing on the due date design, you can leave the attachments and conditional colouring etc...for another issue).

Staff need to be able to define a due date for a pet task. Not all tasks require a due date.

Acceptance criteria
- Tasks db table has new column called `due_date` type `datetime`
- new/edit task form has a date picker where due date can be selected
- index table has Due Date column showing due date value
- overdue tasks should be easy to identify as overdue if the task is not completed (I suggest using the 'expired' marker from [this page of the Geeks theme](https://geeksui.codescandy.com/geeks/pages/student-subscriptions.html) and placing it next to the date value in the Index table saying 'Overdue'). Maybe a Task model scope to check if a task is overdue or not is a suitable approach.
- tests

Note, I suggest a PR for this issue be made after this PR to modify how we write migrations is approved and merged: https://github.com/rubyforgood/pet-rescue/pull/400

**Comment by edwinthinks** [comment]
I can tackle this one!

**Comment by kasugaijin** [comment]
Hey @edwinthinks I am unassigning you so we can get someone else to finish this off. Thanks for doing most of it :)

**Comment by kasugaijin** [comment]
@nsiwnf this issue is still alive! Pr just needs finishing.
