### ISSUE TITLE
As admin I can toggle on/off to disable staff members on staff index table

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#410]
Similar to how we toggle on/off Pause Applications in Pets index table, we should do the same for the Staff index table so an admin can toggle on and off to disable/enable a user

Acceptance Criteria
- Staff Index table column name is 'Disabled'
- Use toggle button with turbo stream to update this attribute dynamically (see Pause Applications for how to)

![image](https://github.com/rubyforgood/pet-rescue/assets/95949082/7a548e73-8202-45ef-b3b6-6f2e7a758cb1)

**Comment by MooseCowBear** [comment]
I can work on this
