### ISSUE TITLE
When uploading a user avatar that it not an image file, application crashes

### ISSUE THREAD

**Issue by jp524** [rubyforgood/pet-rescue#413]
User avatar pictures should only be in JPEG or PNG format according to `app/models/concerns/avatarable.rb`. However, when I try to upload an invalid format like PDF, the application crashes.

Video:
https://github.com/rubyforgood/pet-rescue/assets/85654561/c8b6e75a-378c-41d6-aba9-25b114922398

Screenshot of error screen:
<img width="1448" alt="Screenshot 2024-01-04 at 16 21 37" src="https://github.com/rubyforgood/pet-rescue/assets/85654561/62924fed-d6a8-4888-8b88-bfa640374108">

**Comment by jmilljr24** [comment]
I was able to replicated the issue. It will also give the same error if an image is outside the size limit. If you conditionally display the link_to delete avatar the validations work and are displayed. 
```
      <% if resource.avatar.id %>
        <%= link_to t('general.delete'),
                  purge_attachment_path(resource.avatar.id),
                  data: { turbo_method: "delete" },
                  class: 'delete-button' %>
      <% end %>
```

[Screencast from 01-05-2024 06:40:02 PM.webm](https://github.com/rubyforgood/pet-rescue/assets/16829344/aed067e2-87ce-4970-a91d-ca0cacf1e4a2)

However that doesn't really fix the issue. The avatar_form partial already has a condition to check for an attached avatar. So the server-side validations work. Maybe there is way to do client-side validations or change how it redirects after an invalid file. I'm not sure.

**Comment by jmilljr24** [comment]
Disregard most of my previous comment.

I believe I have a fix if you want to assign me to this. In the avatarable_form partial, the `<% if resource.avatar.attached? %>` is returning true after the redirect to the form when validation errors occur for file type/size. I'm not sure exactly why that happens but simply changing the condition to `<% if resource.avatar.id %>` resolve the issue.

[Screencast from 01-05-2024 08:49:14 PM.webm](https://github.com/rubyforgood/pet-rescue/assets/16829344/65c86cf6-dace-459f-b345-a4a3d7caf449)

**Comment by jp524** [comment]
Thank you @jmilljr24 for looking into this!
I don't have permissions to assign the issue to you though - one of the maintainers has to do it.

**Comment by kasugaijin** [comment]
Thank you @jp524! Assigned to @jmilljr24
