### ISSUE TITLE
As staff I can create a task without a description, and create a default pet task without a description

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#417]
Requiring a description on a Task or DefaultPetTask is unnecessary as there are tasks where just a name is enough. Forcing a user to enter a description is not great UX.

Acceptance Criteria
- Remove model validation on `Task` for `description`
- Remove model validation on `DefaultPetTask` for `description`
- Remove the `null: false` constraint on deault_pet_tasks table for `description` 
- update tests to reflect change

**Comment by atbalaji** [comment]
Hi @kasugaijin , I would like to work on this issue.

**Comment by kasugaijin** [comment]
All yours @atbalaji

**Comment by atbalaji** [comment]
I have a doubt. Should i be adding new test cases for this use case like adding new :default_pet_task in Factory Bot with no description and adding a unit test ?

**Comment by kasugaijin** [comment]
I don't think it's necessary to add any new tests. Just update the model tests to remove the validation.
