### ISSUE TITLE
Investigate possible flaky tests

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#418]
I have run the remote main branch pipeline multiple times and it passes. However, a few PRs are getting failed tests, seemingly flaky as sometimes they pass and do not. Further, if I run main branch tests locally `rails test:all`, sometimes it passes, other times a test will fail...typically it is:
`Organizations::HomeControllerTest#test_: GET #index should render index template`
`UsersTest#test_user_can_log_out`
`LoginTest#test_: when logging in as a staff member should direct to the organization's pets index view.`

Can someone please try running main branch tests locally and see what you get? And if inclined, see why this might be happening.

**Comment by MooseCowBear** [comment]
Some preliminary results from running the tests on my machine, repeating each of the following runs 50 times each:

```test:all``` Returns the greatest number of failures. I also get a errors saying no file is found for some of the controller tests some of the time. 27 out of 50 contained fails/errors about files not being found, plus 4 out of 50 produced Ferrum:StatusError (not sure what this means or why it's happening and google is not helping)

```test``` Returns 1 failure and 7 errors out of 50. 

```test:system``` 2 failures out of 50.

```test test/system/login_test.rb``` No failures. One Ferrum:StatusError toward the end of the run.

I don't know that I'm equipped to diagnose the cause of flaky tests, but it feels like maybe the greater number of failures/errors when running the full test suite could be a clue?

**Comment by kasugaijin** [comment]
Awesome thank you @MooseCowBear for taking a look and verifying!

**Comment by jmilljr24** [comment]
Just to add so more info if it helps, my PR failed three times before finally working. Once was the HomeControllerTest and twice with PetsControllerTest. No issues locally. I can't really offer any other insight.

```
 Error:
  Organizations::PetsControllerTest#test_: POST #attach_images should attaches an image and redirects to pet photos tab with success flash. :
  Errno::ENOENT: No such file or directory @ rb_sysopen - /home/runner/work/pet-rescue/pet-rescue/tmp/storage/sh/q5/shq5ctzwe0orbwscyu5rjtbcenmh
```
```
  Error:
  Organizations::HomeControllerTest#test_: GET #index should render index template. :
  ActionView::Template::Error: undefined method `city_town' for nil:NilClass
  
            <h1 class="display-2 fw-bold mb-3">Rescue pets in '.freeze;@output_buffer.append=( Current.organization.location.city_town );@output_buffer.safe_append=' at <u class="text-warning"><span class="text-primary"> '.freeze;@output_buffer.append=( Current.organization.name );@output_buffer.safe_append='</span></u></h1>
```

**Comment by kasugaijin** [comment]
Thanks @jmilljr24 for additional context. I too have seen failures with the same error. For some reason, sometimes, the Location does not exist. Something to investigate.

**Comment by MooseCowBear** [comment]
I think I might have found a fix for the flaky system tests (although not the others...yet). Switching from `assert_equal current_path, pets_path` to `assert has_current_path?(pets_path)` for both the `UsersTest#test_user_can_log_out` and the `Login Test` looks like it might resolve the issue. I tested on 50 runs. From what I've been able to find, it looks like has_current_path? will wait and try again if it failed. 

I can make this update if you want.

**Comment by kasugaijin** [comment]
Awesome @MooseCowBear! Thank you for looking into these. Looks like you confirmed my suspicion that running tests multi-threaded was exposing a deficiency. I think it's better we modify the tests/setup to work in a multi-threaded environment rather than run single threaded. Please do make a PR with your changes. We can keep an eye on the pipeline thereafter to confirm it's fixed.
