### ISSUE TITLE
Deleting a pet task does not update the list asap.

### ISSUE THREAD

**Issue by atbalaji** [rubyforgood/pet-rescue#422]
Deleting a pet task does not update the list asap. It requires a page reload for UI to update. This may delete to user confusion and also cause double delete of a same task thus resulting in Content missing appear on the page (See at the end of the attached video)

https://github.com/rubyforgood/pet-rescue/assets/18101543/0089498b-8f42-472c-98b2-54ed0492dff8

**Comment by Tomaszabc** [comment]
Hi. I want to work on this issue.

**Comment by atbalaji** [comment]
Would it be good we have a controller testcase that pass only after this fix ?

**Comment by Tomaszabc** [comment]
> Would it be good to have a controller testcase that pass only after this fix ?

Yes. That will be good. I will work on this and add tests also.

**Comment by kasugaijin** [comment]
Ah something has gone wrong with the turbo stream. Please keep this functionality dynamic i.e. fix the turbo stream.
