### ISSUE TITLE
UI updates on Pet Overview Tab 

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#428]
Change the layout of the Pet Overview tab. 
- move the delete button up next to Edit button
- Put Attributes in a table, single row
- **Correction** the image shows the table below the description text. But, we want the description text below the table of attributes

![image](https://github.com/rubyforgood/pet-rescue/assets/95949082/4697d01c-514a-4c3b-9abc-268efa095b3a)

**Comment by DreamVenerable** [comment]
Can I take this issue?

**Comment by kasugaijin** [comment]
@DreamVenerable sure!
