### ISSUE TITLE
Link names to corresponding profiles

### ISSUE THREAD

**Issue by nsiwnf** [rubyforgood/pet-rescue#429]
As a staff member, if I click an adopter name or pet name in the Applications table, I should be redirected to the corresponding profile.

<img width="800" alt="Screen Shot 2024-01-09 at 6 22 25 PM" src="https://github.com/rubyforgood/pet-rescue/assets/34173394/1eaff2b5-d656-4070-8a5b-37bb61ce7756">

**Comment by atbalaji** [comment]
I would love to work on this issue . I have a doubt though.  Just next to **applicant name** we have a **profile icon** linking to the adopter profile. So I am wondering how to avoid redundancy here . Should we have both or remove which one ?

**Comment by nsiwnf** [comment]
Yeah totally, theres another ticket to remove that column so lets just update links for now
