### ISSUE TITLE
Update "New adoption" button

### ISSUE THREAD

**Issue by nsiwnf** [rubyforgood/pet-rescue#431]
As a staff member, I want to be able to create a new adoption for "successful applicants" from the applications table. 

Ex. This is a rough mock - Reuse existing button components for the actual app
<img width="762" alt="Screen Shot 2024-01-09 at 6 34 15 PM" src="https://github.com/rubyforgood/pet-rescue/assets/34173394/87376fc4-ee55-4323-ad9c-49dfd57379e3">

**Comment by jmilljr24** [comment]
Can I be assigned to this?
