### ISSUE TITLE
Remove redundant pet name

### ISSUE THREAD

**Issue by nsiwnf** [rubyforgood/pet-rescue#432]
Remove the pet's name in the card under the "applications" tab since it already appears in the page. This partial is reused in the more general "Adoption Applications" table and we do want to keep the pet name there.

 
<img width="600" alt="Screen Shot 2024-01-09 at 6 42 28 PM" src="https://github.com/rubyforgood/pet-rescue/assets/34173394/d02aa085-ad69-4766-b400-f30749d51b37">

**Comment by mayankbhatt07141** [comment]
Hey @nsiwnf  I want to work on this, Please assign this to me.
Thanks
