### ISSUE TITLE
Update design picture/file upload

### ISSUE THREAD

**Issue by nsiwnf** [rubyforgood/pet-rescue#433]
Update the picture/file upload components to match this design. Remove "Save" and add "Attach" and keep the same functionality.

<img width="773" alt="Screen Shot 2024-01-09 at 6 46 51 PM" src="https://github.com/rubyforgood/pet-rescue/assets/34173394/34cddbc0-f3c5-46f5-b632-9007c3c2e62a">

**Comment by DreamVenerable** [comment]
So basically rename the button and move it up? Can I do it?
