### ISSUE TITLE
Remove "Profile" column in Adoption Applications view

### ISSUE THREAD

**Issue by nsiwnf** [rubyforgood/pet-rescue#441]
Remove this "Profile" column since the Applicant already links to the profile.

<img width="419" alt="Screen Shot 2024-01-17 at 3 39 44 PM" src="https://github.com/rubyforgood/pet-rescue/assets/34173394/2bd0a2aa-592b-42ab-b717-ad0b98f67515">

**Comment by nsiwnf** [comment]
@atbalaji  I thought there was an existing ticket for this, but looks like there's not - just created it if you want to pick this up!

**Comment by atbalaji** [comment]
@nsiwnf I would like to take this issue

**Comment by atbalaji** [comment]
I am not sure about the reason for this https://github.com/rubyforgood/pet-rescue/blob/92a52ab2ed18813fd30f4c2448d0f6ef06e8a1b6/app/views/organizations/pets/tabs/_applications.html.erb#L28 . If it is needed should we have the same condition for the link through applicant name

**Comment by nsiwnf** [comment]
@atbalaji  I'm not sure either but I don't think it's needed now

**Comment by kasugaijin** [comment]
> I am not sure about the reason for this
> 
> https://github.com/rubyforgood/pet-rescue/blob/92a52ab2ed18813fd30f4c2448d0f6ef06e8a1b6/app/views/organizations/pets/tabs/_applications.html.erb#L28
> 
> . If it is needed should we have the same condition for the link through applicant name

This should only be a condition for displaying the 'Create Adoption' button. Should not be an issue for the Profile column.
