### ISSUE TITLE
Foster Epic: rename AdopterProfile to AdopterFosterProfile

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#448]
We currently have the AdopterProfile model, but this will also be used by fosterers, so let's rename it to AdopterFosterProfile. 

Acceptance criteria
- rename model, associations on other models, and all instances of its us in the application
- tests pass

**Comment by atbalaji** [comment]
I would like to work on this issue @kasugaijin

**Comment by kasugaijin** [comment]
All yours @atbalaji 
I will add you!

**Comment by atbalaji** [comment]
Should we care about separate commits and deploy like first migration for renaming the table  and then code changes so as not to cause possible errors during deploy. Or it doesn't matter.
Would like to hear your thoughts.

**Comment by kasugaijin** [comment]
I think it's a good idea to make a commit with migration and schema changes, then add code changes in later commits @atbalaji

**Comment by atbalaji** [comment]
Hi @kasugaijin ,Shall I change AdopterProfilesController to AdopterFosterProfilesController too ? or keep it as it is and add controller options to resources :adopter_foster_profile

**Comment by kasugaijin** [comment]
@atbalaji how's this one going?

**Comment by kasugaijin** [comment]
@atbalaji bump - are you still working on this? No pressure :)

**Comment by atbalaji** [comment]
Hi @kasugaijin . Sorry for no response. I was occupied and unable to spend time here. I'm done with migration and code changes in few areas before break.I can get back to this issue today and get a PR within 1-2 days.

**Comment by atbalaji** [comment]
I have some doubts.  What to do with the use of adopter_profile in instance variable names like @adopter_profile, html id names, locales, comments though logically changing associations and models and related usage will be fine.  Should i change them ? Reason for doubt is it will result in touching a lot of file areas. Just want to know the scope of the change .

**Comment by kasugaijin** [comment]
Hey @atbalaji no worries at all! Not rushing you, just making sure you have what you need.
 

> I have some doubts. What to do with the use of adopter_profile in instance variable names like @adopter_profile, html id names, locales, comments though logically changing associations and models and related usage will be fine. Should i change them ? Reason for doubt is it will result in touching a lot of file areas. Just want to know the scope of the change .

Will a simple find and replace work in this case? I think it should be quick and easy.

**Comment by atbalaji** [comment]
Yeah. A find and replace would work in this case. I tried it initially but the only thing I am worried about is it will inevitably touch a lot of areas in code. Also if the test coverage is not enough or in case meta programming is used in some cases involving adopter profile, it may give birth to unknown errors in other areas of app. That was my point of concern.

**Comment by kasugaijin** [comment]
@atbalaji I think it should be OK. You can skip making changes in any skipped tests. We will need to invest more time into the adopter/foster profile once the custom form buikder is in place so if something breaks its is not a major problem.
