### ISSUE TITLE
Foster epic: Create AdopterFosterAccount

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#449]
~~Blocked by https://github.com/rubyforgood/pet-rescue/issues/448~~

~~We differentiate user types in this app by associating `User` with either `AdopterAccount` or `StaffAccount`. We need to add a third user type `FosterAccount`.~~

To add the Foster we will rename the AdopterAccount to AdopterFosterAccount as well as its corresponding table and code references.

Acceptance criteria
- Rename the adopter_accounts table to adopter_foster_accounts
- Rename the model 
- Keep same model associations but update names (belongs_to user, User has one adopter_foster_account)
- Update code references of adopter_account and AdopterAccount
- Tests pass

**Comment by ErinClaudio** [comment]
I have started this but I will have follow-up questions.

**Comment by kasugaijin** [comment]
@ErinClaudio for sure
Note you'll want to wait for this issue https://github.com/rubyforgood/pet-rescue/issues/448 to be merged so we can add the association to the adopter_foster_profile on FosterAccount model.

**Comment by kasugaijin** [comment]
Draft PR in progress: https://github.com/rubyforgood/pet-rescue/pull/452

**Comment by ErinClaudio** [comment]
https://gist.github.com/ErinClaudio/372b5d6e6bb03b3d604ab934a8c563ac

**Comment by ErinClaudio** [comment]
https://gist.github.com/ErinClaudio/372b5d6e6bb03b3d604ab934a8c563ac
