### ISSUE TITLE
Failures in creating a staff account causes the user to be directed to adopter registration form.

### ISSUE THREAD

**Issue by edwinthinks** [rubyforgood/pet-rescue#45]
https://jam.dev/c/d57a633f-46e0-4636-935d-8511ea022d4c

**Comment by heyapricot** [comment]
Since we removed the ability to create staff accounts this no longer makes sense:

PR to remove staff account creation: https://github.com/rubyforgood/pet-rescue/pull/109

**Comment by heyapricot** [comment]
Also: https://github.com/heartcombo/devise/issues/5113

**Comment by Thrillberg** [comment]
🎉
