### ISSUE TITLE
Implement authorization framework

### ISSUE THREAD

**Issue by mononoken** [rubyforgood/pet-rescue#450]
Currently, authorization is not handled consistently. This issue would address this by implementing an authorization system via the gem [Action Policy](https://github.com/palkan/action_policy). This would set up a framework to unify authorization logic as well as help guide devs to set up future authorization logic.

### Implement
- [x] Add Action Policy gem
- [x] Implement `verify_authorized` is called in `ApplicationController` to force all controller actions to require authorization
- [x] Create Policies for every controller that requires them. Use `skip_verify_authorized` for actions that should not require authorization. `ActionPolicy::UnauthorizedAction` error should never raise in production.
- [ ] Have another contributor create and implement a policy to confirm ease of use with `Action Policy` gem for others.
### Testing
- [x] Create test file for each Policy class created.
- [x] Create controller tests to test the required authorizations are performed.

Notes:
- Since `Rolify` is being used, these roles should be integrated with authorization checks.
- If Action Policy is deemed to not fit well, we can migrate most of this logic over to [Pundit](https://github.com/varvet/pundit) instead.

I will start working on this now. Please assign me if you have permission. Thanks!

**Comment by kasugaijin** [comment]
@mononoken great thank you for taking the initiative! This will be a great addition.

**Comment by mononoken** [comment]
#466 is working on this one. Can someone add it to the development of this issue? I think that will prevent the bot from marking this as stale.

**Comment by kasugaijin** [comment]
> #466 is working on this one. Can someone add it to the development of this issue? I think that will prevent the bot from marking this as stale.

Done!
