### ISSUE TITLE
Pet Task Epic: Change design and move the 'create new task' button 

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#453]
For Pet Tasks tab, the Create New Task should look like and be positioned as it is here.
Refer to the theme for styling: https://geeksui.codescandy.com/
See Tasks V2 for design: https://www.figma.com/file/0jVgYASUJy0KiX3BVc3dFM/Tasks?type=design&node-id=0%3A1&mode=design&t=vyTdeotEtckQCTFB-1

![image](https://github.com/rubyforgood/pet-rescue/assets/95949082/4b565f3f-073d-4223-b56e-33ac1a812f69)

**Comment by sparshalc** [comment]
Can i do this?

**Comment by kasugaijin** [comment]
@sparshalc of course!
