### ISSUE TITLE
Pet Task Epic: Add colour shading to background of each task depending on its 'status'

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#454]
Completed pet tasks should show green, uncompleted and not overdue should remain white, and uncompleted and overdue should be shaded red, per the image.
Refer to the theme for styling: https://geeksui.codescandy.com/
See Tasks V2 for design: https://www.figma.com/file/0jVgYASUJy0KiX3BVc3dFM/Tasks?type=design&node-id=0%3A1&mode=design&t=vyTdeotEtckQCTFB-1

![image](https://github.com/rubyforgood/pet-rescue/assets/95949082/0f5b166b-1fe5-4b91-a64b-e8fc052c8f73)

**Comment by tmorton** [comment]
👋 I'd like to do this tomorrow.

**Comment by kasugaijin** [comment]
@sparshalc I see you have put up a PR for this. Please in future only put up PRs for issues that you assigned to. Someone else was going to take this one. Not a problem..just a rule for open source.

**Comment by kasugaijin** [comment]
@sparshalc thank you!
