### ISSUE TITLE
Pet Task Epic: As staff I can use a toggle to update the pet task list to show/hide completed tasks

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#455]
As staff I can use a toggle to update the pet task list to show/hide completed tasks.
This should be implemented dynamically with Hotwire.
Toggle should be designed and placed as shown.

Refer to the theme for styling: https://geeksui.codescandy.com/
See Tasks V2 for design: https://www.figma.com/file/0jVgYASUJy0KiX3BVc3dFM/Tasks?type=design&node-id=0%3A1&mode=design&t=vyTdeotEtckQCTFB-1

Completed shown
![image](https://github.com/rubyforgood/pet-rescue/assets/95949082/57d41fa7-5685-485d-933a-80f35659f6e3)

Completed hidden
![image](https://github.com/rubyforgood/pet-rescue/assets/95949082/ac660fff-09f7-4685-a65c-33e2907ac8df)

**Comment by sparshalc** [comment]
I'd love to give this a try!

**Comment by kasugaijin** [comment]
All yours @sparshalc

**Comment by sparshalc** [comment]
It would be wise to examine pull request #460 before moving forward with this matter, correct? @kasugaijin

**Comment by kasugaijin** [comment]
@sparshalc i left a review on that PR. Not sure if you saw it? I think there has been an issues with visibility or notifications when someone requests a review a few times now.

**Comment by kasugaijin** [comment]
@sparshalc oh weird! I will copy and paste it to a comment!

**Comment by kasugaijin** [comment]
@sparshalc this issue is now unblocked!
