### ISSUE TITLE
Pet Task Epic: As staff I can create a default pet task with a due_in_days value

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#456]
Default Pet Tasks are used to create new Tasks for each new Pet. Currently, Default Pet Tasks require a name and description. We need another attribute, called `due_in_days` that will be used to calculate the due date of a Task i.e., `due_date` of a Task = `Time.current + due_in_days` of a Default Pet Task

Acceptance Criteria:
- migration to add new column to Default Pet Tasks table, integer
- model validation that user enters integer
- add to Default Pet Task form in UI (optional field)
- update the DefaultPetTaskService to create tasks with a due date if a default pet task has a `due_in_days` value
- update the seed data so at least one task is overdue, and one task is completed, and one task is not overdue
- tests

**Comment by tmorton** [comment]
👋 I'd like to take this.
