### ISSUE TITLE
Default tasks with blank description causes error when creating a pet

### ISSUE THREAD

**Issue by tmorton** [rubyforgood/pet-rescue#462]
**Summary**

The problem here is that default tasks have an optional `description`, while the field is mandatory on tasks.  So we fail to create a pet when there is a default task with a blank description.

**How to reproduce**

- Create a default task with a blank description ( http://127.0.0.1:3000/alta/default_pet_tasks/new )
- Create a new pet ( http://127.0.0.1:3000/alta/pets/new )
- You will get an "Error creating pet" 

**Notes**

My suggestion is to make the field on tasks optional (remove the Rails validation in the `Task` model).  I imagine that many tasks don't need a description (ie "Give anti-flea medicine").  

This may be a good "first issue".

Discovered while working on #456

**Comment by kasugaijin** [comment]
I agree with the above! No need to enforce a description on tasks. Thank you for making the issue @tmorton .

**Comment by kasugaijin** [comment]
@jmilljr24 thank you!
