### ISSUE TITLE
Pet Task Epic: As staff I see uncompleted pet tasks above completed pet tasks.

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#471]
Acceptance criteria:
- Uncompleted pet tasks show above completed pet tasks. 
- Uncompleted tasks with a due date show above uncompleted tasks without a due date, and are ordered by due date (ascending) so the closest (or most overdue) due dates show higher. 
- Uncompleted tasks without a due date are ordered with most recent being placed higher (created_at and/or updated_at) (open to alternative ideas here also)
- Completed tasks are ordered the same as above based on due date, or date created/edited.

Currently we are ordereing tasks by making a query in the view. Now that we have a bit more complexity, it's probably better to move this to the Task model and do the ordering of the collection with a scope or method that we can call in the view.

**Comment by jmilljr24** [comment]
I'd like to work on this.

**Comment by kasugaijin** [comment]
@jmilljr24 all yours
