### ISSUE TITLE
Org Page Content Epic: create a table and model to store text used by orgs to populate their public pages.

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#473]
Each organization in this application needs to be able to customize certain content (text and images) on certain public pages in order to make the site relevant to them. For example, each organization should be able to edit, update their own root page Hero text, as well as the root page  Who We Are section. See Landing Page V2 here: https://www.figma.com/file/0jVgYASUJy0KiX3BVc3dFM/Tasks?type=design&node-id=0-1&mode=design

Acceptance Criteria: 
- Create table PageTexts with columns `organization_id` (foreign key and index) , `hero` (string), `about` (text) both of these should default as `null` 
- Create model `PageText` (belongs to `Organization`, but use the `acts_as_tenant` method - see `Pet` for example) 
- We should be able to create a new PageText that belongs to an org and has nil values for `hero` and `string`. The Model validation should ensure that an empty string `''` is not valid, however. My thinking here is that when an org first signs up, this record will be created and the the string values will be `nil`. When the org edit/save their custom strings, we don't want empty strings. In the view we can check if this attribute is `nil` and if so, use default text in the view file, else use their custom string. Open to other ideas here. Something like `presence: { allow_blank: false }` might work fine.
- Add creation of PageText to the `Organizations::CreateService` so it is created when a new org is created
- Add creation of PageText (just nil values for hero and about is fine) to seed files for both orgs

**Comment by MooseCowBear** [comment]
I can work on this

**Comment by kasugaijin** [comment]
@MooseCowBear all yours!
