### ISSUE TITLE
Org Page Content: Org can create their own FAQ

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#474]
Every organization is going to need to be able to CRUD a simple FAQ. This ticket is to build to table and model so a dev can CRUD FAQs for an org in the console.

Acceptance Criteria
- Create table for the FAQ that has `organization_id` (index and foreign key) `question` string, `answer` text and `order` integer (order used to sort in the UI). Question and answer should be null false, order is optional.
- Create FAQ model. FAQ should belong to organization (use acts_as_tenant method - see Pet.rb for example). Both question and answer are required so validate accordingly.
- Dev should be able to CRUD FAQs for an org in console
- Add tests

**Comment by atbalaji** [comment]
Hi @kasugaijin , I would like to work on this issue. Is it still available ? also what does the snack label mean?

**Comment by kasugaijin** [comment]
All yours @atbalaji ! Snack is just a way to quantify the amount of work. A snack is smaller than a meal :D

**Comment by kasugaijin** [comment]
How's this going @atbalaji ? Let me know if you have any questions!

**Comment by kasugaijin** [comment]
Hey @atbalaji I will unassign you to open this up if I don't hear from you in the next day or so. Thanks!

**Comment by jmilljr24** [comment]
I can work on this if you'd like.

**Comment by kasugaijin** [comment]
Sounds good @jmilljr24 !
