### ISSUE TITLE
Org Page Content Epic: As org staff I can go to the dashboard and input text that will update the hero and about us Part 1

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#479]
https://github.com/rubyforgood/pet-rescue/pull/476 added a new table and model for PageText. Now we need to add the controller, routes and views to enable staff to go to their dashboard and be able to CRUD the hero text and about us text. 

Acceptance criteria:
- Add the PageText controller (scoped under organization like PetsController)
- Add edit and update actions (see organizations > organization profile controller for example)
- Add routes for these actions (again use org profile as a guide)

If you want to also do part 2 of this work on the views at the same time, feel free to take on both tasks at once.

**Comment by phonghpham** [comment]
@kasugaijin, I can tackle this and part 2!

**Comment by kasugaijin** [comment]
Of course! @phonghpham Assigned.
