### ISSUE TITLE
Org Page Content Epic: As org staff I can go to the dashboard and input text that will update the hero and about us Part 2

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#480]
Blocked by https://github.com/rubyforgood/pet-rescue/issues/479 but if you want to take on both at the same time, feel free!

This issue is to add the views that enable an org staff to edit and update their page text. 

Acceptance Criteria
- Add new link 'Page Text' in the dashboard navbar under Default Pet Tasks link that goes to the PageText edit action/view that renders the form (similar to how clicking Settings takes you to the edit form for the org profile)
- Create form with inputs for Hero Text and About Us
- It should look similar to below, including header and breadcrumb
- Update the hero text and about us section on the root page so that if hero text or about us text is not nil for PageText it renders the org's custom text, otherwise renders the existing default text.

<img width="1496" alt="image" src="https://github.com/rubyforgood/pet-rescue/assets/95949082/21490cec-0d6f-405e-9728-9c6e98a5d218">

**Comment by nsiwnf** [comment]
@kasugaijin can you include a screenshot of where "Hero" and "About Us" text shows up? I see a couple places that have "About Us"

**Comment by kasugaijin** [comment]
@nsiwnf yes good point...does this help enough?
![Untitled design](https://github.com/rubyforgood/pet-rescue/assets/95949082/be0fd942-f53f-4f5b-b2f0-317b6dcc5a77)

**Comment by kasugaijin** [comment]
@phonghpham I need to add you here so I can assign you. Done.

**Comment by kasugaijin** [comment]
@phonghpham I for some reason could not assign you so assigned myself. But this ticket is all yours to do!

**Comment by phonghpham** [comment]
Copy that!
