### ISSUE TITLE
Remove ability for user to delete their account in the UI

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#481]
we have a section to delete account on the user registration/edit view and we can get rid of it (everything under and including the unhappy?)
![image](https://github.com/rubyforgood/pet-rescue/assets/95949082/59c767b3-1c3e-48ad-b142-be08c62b6697)

**Comment by kasugaijin** [comment]
Issue is for Mason Roberts.

**Comment by Developer3027** [comment]
Thank you. Will review.
