### ISSUE TITLE
Fix recurring task with a due date

### ISSUE THREAD

**Issue by mononoken** [rubyforgood/pet-rescue#501]
While merging main to the authz feature branch, I noticed a failing system test for tasks. It appears to be failing on main too.

```
TasksTest#test_creates_a_recurring_task_with_a_due_date_without_redirecting [test/system/tasks_test.rb:25]:
expected to find text "Due Date - 07 Mar" in "Wisozk, Mertz and Harber MENU Dashboard Adoption Applications Foster Applications Pets Default Pet Tasks AL Baby Home Pets Baby Overview Tasks Applications Photos Files Tasks Add New Task Show Completed Recurring Task Recurring task description Due Date - To
day Edit Delete"

rails test test/system/tasks_test.rb:12
```

I tried:
1. Drop the DB and re-run bin/setup
2. Open http://localhost:3000/alta/pets/1/tasks/new and try to create recurring task

It looks like this is probably failing because the form does not allow you to set `Next due date in (days)`, even when `Recurring` is checked. 

Can someone confirm this error? (Note: You need to run `bin/rails test:all` to include system tests in the test run.) It may be an easy fix too. 

![test-sys-task](https://github.com/rubyforgood/pet-rescue/assets/81536479/642eb33e-fc2f-4b60-9b99-1fe9935d5de5)

**Comment by mononoken** [comment]
> @mononoken Hmm, I've run multiple batches and haven't reproduced the failure yet. And manually, if I set both a due date and check recurring to be true, the due date in days field becomes enabled.
> 
> Edit -- I see what's happening. The due date of the task is being displayed as "Due Date - Today" instead of in the form of "Due Date - #{due_date.strftime("%d %b")}" which the assert statement is looking for. We could switch the test's due date to be further out than one day.

Good catch, @MooseCowBear ! I am not getting the failure now either. I think one possibility is the failure is related to time zones and time of day. If that's the case, an alternate approach to fixing could be to mock the times or use the built in ActiveSupport::Testing::TimeHelpers. Could also just be something on my end too though unless someone can replicate the failure.

**Comment by MooseCowBear** [comment]
@mononoken I would guess it is related to time zones but even if it isn't it seems better to mock the time or use the testing helpers like you said.

**Comment by mononoken** [comment]
Finally getting back to this. I am realizing this is an indication of a bug with Tasks. 

As @MooseCowBear pointed out, the test was failing because the `due_date` was rendering as `Today`, not the `strftime` format the test expects.

But, why is the due date today when it was just set to tomorrow?
```ruby
    due_date = (Date.today + 1.day)
```

I just checked in the live app as well, and it looks like tomorrow dates render as `Today`. I haven't looked yet at the view or anything else yet, so the answer may be obvious. I am gonna get some sleep now though. 

If anyone else would like to tackle this, let me know and I can assign you. Otherwise, I'll see if I can look more into it later.

**Comment by MooseCowBear** [comment]
@mononoken I think I found the source of the problem, for the test at least. I think the problem is that `Date.today` is relative to the OS date/time. Whereas `Date.current` seems to give the date in UTC (the time zone of the app). I can see the two diverge in the Rails console when I change my computer's time zone. If you change the test to use Date.current, does the issue resolve for you?

**Comment by mononoken** [comment]
> @mononoken I think I found the source of the problem, for the test at least. I think the problem is that `Date.today` is relative to the OS date/time. Whereas `Date.current` seems to give the date in UTC (the time zone of the app). I can see the two diverge in the Rails console when I change my computer's time zone. If you change the test to use Date.current, does the issue resolve for you?

Good find @MooseCowBear ! That does fix it for me.

Based on that, I think the tests should probably be using `Date.current` and the views should be using `Date.today`. Do you agree?

If you want to go and make those changes to `test/system/tasks_test.rb` and `app/views/organizations/tasks/_task.html.erb`, I will approve and push them. Thanks for doing all the lifting on this one 😁

**Comment by MooseCowBear** [comment]
@mononoken Sorry for the late response. The notice got buried in my email. 

I think that's right. I'll make the changes.
