### ISSUE TITLE
org root update part 3 adopt

### ISSUE THREAD

**Issue by Developer3027** [rubyforgood/pet-rescue#505]
Update the org / root to the V2 specifications  of the figma file. Review the [Figma file](https://www.figma.com/file/0jVgYASUJy0KiX3BVc3dFM/Tasks?type=design&node-id=0-1&mode=design&t=vgtXd4mbcs2Xqstn-0). This section has a title, four cards, and the browse link.

**Comment by Developer3027** [comment]
Reviewing

**Comment by nsiwnf** [comment]
@Developer3027  is this issue complete? :)

**Comment by Developer3027** [comment]
Complete
