### ISSUE TITLE
Pet Task Epic: As staff I can create a default pet task that is recurring and set the 

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#508]
Staff can currently create Default Pet Tasks. These are tasks that are automatically created on new pet, when that pet is created. This is for common tasks that always apply, and saves the staff from having to manually create them on each pet.

Tasks now have recurring functionality. That is, staff can create/edit a task on a pet and set it as recurring, and also set a next_due_date_in_days value. When this recurring task is marked complete, a new, identical task is created, and its due date will be today + the next_due_date_in_days value. 

This ticket is to add ~~two~~  a new attribute to Default Pet Tasks that will create recurring tasks on a pet. 

Acceptance criteria:
Add to DefaultPetTask (table, model, form)
- Migration to add recurring, boolean ~~and next_due_date_in_days, integer~~ to the default_pet_tasks table
- Add recurring, checkbox, and ~~next_due_date_in_days, positive integer input~~ to the default pet tasks form
- Add new attr to accepted params in controller, and if it makes sense, validate that due_in_days is positive on the model
- Update the TaskService to create the first task. Due date will be Time.current + due_in_days, and Task's next_due_in_days will be the Default Task's due_in_days
- Update tests

**Comment by nsiwnf** [comment]
Do we need design for this? Seems like staff needs some sort of UI to manage default tasks

**Comment by nsiwnf** [comment]
I feel like there could be different scenarios for default pet tasks? 
ex.
On add pet (draft mode) -> add tasks: fill in pet details (not recurring), vaccine reminders (recurring)
On app submitted for pet -> add tasks: review application (not recurring)

**Comment by kasugaijin** [comment]
@nsiwnf there’s already a default pet task flow in main for staff to add default pet tasks (see dashboard sidenav) so this issue shouldn’t need any design. These  are used to create a new task on creation of a new pet.

I do like the idea of tethering other tasks to certain events too, though.

**Comment by kasugaijin** [comment]
Anyone interested in this ticket - let me know if you have questions! Here or in slack.

**Comment by jmilljr24** [comment]
I can work on this. 

Just some clarification.

>     * Update the TaskService to create the first task. Due date will be Time.current + next_due_date_in_days

This is assuming an initial due date was not submitted? Would there be a scenario for example, where the staff would want the initial due date to be 5 days out then the recurrence would be every 10 days going forward? 

Something along the lines of `if task.due_date is nil then Time.current + next_due_date_in_days else task.due_date`

Or would you prefer in the form to disable the due_date field if recurring is selected and enable the next_due_date_in_days?

**Comment by kasugaijin** [comment]
All yours!

So the Default Pet Task form/model doesn't have a due date. We use the due_in_days to calculate the due date in the Service. But this does remind me that my initial ticket is incorrect as we do not need to include a due in days in the migration. We can use the existing field to create the due date and set the next_due_in_days on the Task when it is created. Does that make sense?
<img width="917" alt="image" src="https://github.com/rubyforgood/pet-rescue/assets/95949082/98cf7f5e-4915-4873-b452-50d4f0b6669b">

**Comment by jmilljr24** [comment]
Yes! Thank you.
