### ISSUE TITLE
Pet Task Epic: When I see the form to create a new task I see a Cancel button that closes the form

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#521]
Currently when you create or edit a task on Pet > Tasks tab, the inline form appears, but there is no way to close the form if you don't want to save the task. 

Acceptance criteria:
- add new button to the right of the 'Save Task' button at the bottom of the inline form that is 'Cancel'
- when you click cancel, the inline form closes (using turbo stream to close the form)
![image](https://github.com/rubyforgood/pet-rescue/assets/95949082/55910781-c8b4-47ce-a084-7e7999b72bad)

Cancel instead of Delete but this style - see styling used in the Files or Photos tab for this button.
<img width="127" alt="image" src="https://github.com/rubyforgood/pet-rescue/assets/95949082/6e3eb3ac-e036-40dd-871e-f2d909412922">

**Comment by MooseCowBear** [comment]
I can do this. Maybe we also want to display validation errors? I think currently the task form doesn't report them to the user.

**Comment by kasugaijin** [comment]
@MooseCowBear 100%!
