### ISSUE TITLE
Remove 422 route as "restricted access"

### ISSUE THREAD

**Issue by mononoken** [rubyforgood/pet-rescue#534]
Currently, this route is defined:
```ruby
# routes.rb
match "/422", to: "errors#restricted_access", via: :all
```

I am not sure where this definition came from but `422` should be "Unprocessable Content" (https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422).

I think this could have potentially been a typo for `402` which is "Payment required" which seems closer to "restricted access". Ultimately, though "restricted access" makes me think of `403 forbidden`.

All that said, I don't think this route is currently in use. We could delete it (and associated view and controller action).

 Anyone know what this was for and whether we are good to remove?

**Comment by kasugaijin** [comment]
I do not recall why I added that specific route...and incorrectly named haha. I think we will want to figure out what routes/errors we want to handle moving ahead and refactor accordingly. Always nicer to show custom, branded errors rather than the heroku default.
