### ISSUE TITLE
Fix: "My Applications" view for adopters

### ISSUE THREAD

**Issue by nsiwnf** [rubyforgood/pet-rescue#543]
In the "My Applications" view for an adopter - The pet image is not bound and can take up the whole screen. 

Actual
<img width="200" alt="Screen Shot 2024-03-12 at 9 44 03 PM" src="https://github.com/rubyforgood/pet-rescue/assets/34173394/c1c97521-f66a-4314-a946-3b7753cbe6a0">

---
Expected
<img width="200" alt="Screen Shot 2024-03-12 at 9 51 10 PM" src="https://github.com/rubyforgood/pet-rescue/assets/34173394/fb7e3b0a-7d15-496b-92a1-d2e0368c59a8">

**Comment by mayankbhatt07141** [comment]
Please assign this to me @nsiwnf, I want to work on this.

**Comment by LindseyB** [comment]
Should this be closed as https://github.com/rubyforgood/pet-rescue/pull/594 was merged?
