### ISSUE TITLE
Fix: Menu options when logged in

### ISSUE THREAD

**Issue by nsiwnf** [rubyforgood/pet-rescue#544]
As a user who is logged in, I should see a "Log out" option in the menu

<img width="300" alt="Screen Shot 2024-03-12 at 9 57 42 PM" src="https://github.com/rubyforgood/pet-rescue/assets/34173394/6b98c1ea-dd9a-4a42-800c-a5e554c8b8c5">

**Comment by Tomaszabc** [comment]
I can work on this
