### ISSUE TITLE
Mobile UI: Staff "Pets" view

### ISSUE THREAD

**Issue by nsiwnf** [rubyforgood/pet-rescue#546]
The "pets" view in the dashboard for small screens requires a lot of scrolling

1. go to [demo site](https://pet-rescue-f6df7ce0e850.herokuapp.com/alta/home)
2. login as staff
    email: [staff@alta.com](mailto:staff@alta.com)
    password: 123456
3. go to "Pets" tab in the navbar

https://github.com/rubyforgood/pet-rescue/assets/34173394/f29180de-a138-4646-9b36-781559e80a0a

**Comment by Mar1g0m3z** [comment]
Hello is this issue available to work on? I don't want to step on any toes.

**Comment by nsiwnf** [comment]
Hey @Mar1g0m3z - This issue needs some design/mockups before it can be implemented. Would def appreciate any design feedback if you have it, otherwise any unassigned issue without the "needs design" or "on hold" label is up for grabs!

**Comment by mononoken** [comment]
This page renders as cards now, so I think this is good to close.
