### ISSUE TITLE
Fix: Mobile view for Staff "Review Applications"

### ISSUE THREAD

**Issue by nsiwnf** [rubyforgood/pet-rescue#547]
Some of the buttons disappear in mobile view on the staff's "adoption applications" dashboard page. There is also no way for staff to edit notes and "create adoption" on mobile devices.

1. go to [demo site](https://pet-rescue-f6df7ce0e850.herokuapp.com/alta/home)
2. login as staff 
    email: staff@alta.com
    password: 123456
3. go to "Adoption Applications" tab in the navbar

<img width="300" alt="Screen Shot 2024-03-12 at 10 05 24 PM" src="https://github.com/rubyforgood/pet-rescue/assets/34173394/9258c28b-cf59-4330-b001-c6a4d2c91974">

We should style the content so it renders as cards below 1200 px width. Use `/staff/manage_fosters` as a guide. It would probably be good to do something similar to this:
```erb
<!-- app/views/organizations/staff/manage_fosters/index.html.erb -->
        <!-- Search Results -->
        <%# Table layout %>
        <div class="d-none d-xl-block">
          <%= render "foster_table", foster_pets: @foster_pets %>
        </div>

        <%# Cards layout %>
        <div class="d-xl-none d-flex flex-wrap">
          <%= render "foster_cards", foster_pets: @foster_pets %>
        </div>
```

## Acceptance Criteria
- [x] Page index content renders cards below 1200 px width
- [x] All card content fits on mobile screens
- [x] Applications should be grouped by pet still (again, see `/staff/manage_fosters` design)

**Comment by kasugaijin** [comment]
Just some thoughts for when this is being designed. We could use a table layout like we currently have for larger widths, and for narrower widths, we get rid of the table and instead use cards. I think tables are inherently better consumed on larger screens, and cards are better for smaller screens. My two cents!

**Comment by MooseCowBear** [comment]
Might also want to consider the applications tab on the pets show page, which uses the same partial. Currently there is some overlap there to resolve. 
<img width="1244" alt="Screenshot 2024-05-03 at 4 51 15 PM" src="https://github.com/rubyforgood/pet-rescue/assets/82609260/d72d9361-41f6-414e-bec9-8c06735bec4c">
