### ISSUE TITLE
User accounts: Magic login links

### ISSUE THREAD

**Issue by garyhtou** [rubyforgood/pet-rescue#55]
As an adopter, I can login with a magic link so that I don't have to remember a password

**Comment by Thrillberg** [comment]
I'd like to take this on, if that sounds good! 😄 I'm thinking that we only want these for `staff_accounts`. Is that right? This makes sense for initial sign up but what about subsequent logins? One big question is whether we want any passwords at all. If we totally drop passwords for staff accounts then wouldn't people have to check their email each time they want to log in? That seems more annoying than, for example, having your browser or 1Password remember a password.
