### ISSUE TITLE
Fix: All adopter applications should be visible to staff

### ISSUE THREAD

**Issue by nsiwnf** [rubyforgood/pet-rescue#556]
**Actual**
On the `adopter_applications_review` page, clicking "New Adoption" causes the applications associated with that pet to disappear from the page. Further, they are not included in filter results for pet name or application status 'adopted'. 

**Expected**
As staff, when I click "New Adoption" for an application on the `adopter_applications_review` page, I should still be able to see all the applications for that pet.

**Notes**
Might need to fix ransack query

**Comment by MooseCowBear** [comment]
I can work on this
