### ISSUE TITLE
Display "Featured pets" on the org home page

### ISSUE THREAD

**Issue by nsiwnf** [rubyforgood/pet-rescue#558]
Randomly select 4 of the org's adoptable_pets to display on the home page. 
Change copy under the pet image to "Adopt [pet's name] ->" as shown below.

<img width="500" alt="Screen Shot 2024-03-17 at 6 54 57 PM" src="https://github.com/rubyforgood/pet-rescue/assets/34173394/04822ae0-6daa-4ed5-9410-c259a4e07cf0">

**Comment by DreamVenerable** [comment]
I can take this!

**Comment by VonTeacher** [comment]
@DreamVenerable @nsiwnf Any progress on this? If not, I can take care of it this weekend.

**Comment by DreamVenerable** [comment]
I got busy and totally forgot about it 😅

You are free to take it!

**Comment by VonTeacher** [comment]
OK, thanks for the response. If you want, I can ping you when it's ready for review. :)

**Comment by kasugaijin** [comment]
@VonTeacher All yours!

**Comment by VonTeacher** [comment]
I have a sample of pet cards displaying on the organization's HomeController, but I'm unsure of the best or established pattern in the repository for that query and creation of the instance variable in `app/controllers/organizations/home_controller.rb`, so feedback is particularly welcome.

**Comment by kasugaijin** [comment]
Can you make a draft PR with your approach? It's easier to comment on the existing code and gives you a chance to choose a solution. I see what you mean though, it's a one-off type of query that doesn't relate particularly well to any specific model, enough to put on a model for example. I am not a big fan of putting random methods in controllers, either, so this might be a good use of `app/helpers`?

**Comment by kasugaijin** [comment]
@VonTeacher I will unassign so someone else can finish this off. But, let me know if you want to finish it!

Just a couple comments to address in the PR (delete some tests). It should be a quick fix. https://github.com/rubyforgood/pet-rescue/pull/660

**Comment by meg-gutshall** [comment]
Closed by #784
