### ISSUE TITLE
Make dashboard navbar icon clickable to redirect to org root page

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#572]
Currently, when staff on on the dashboard, they cannot click to return to the org root page.

Make this div clickable so that it takes the user to the root page for the given organization e.g., `petrescue.com/baja/home`

![image](https://github.com/rubyforgood/pet-rescue/assets/95949082/3aca5c1e-e643-43f8-98a7-83d1c6e433d0)

**Comment by pshong79** [comment]
I would like to take this on if possible.

**Comment by mononoken** [comment]
Thank you, @pshong79 ! You are assigned now.
