### ISSUE TITLE
Spike: How can we make the donut chart for the staff dashbord index page?

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#591]
We want to display some charts on the Staff dashboard index to provide quick glance information. Currently in our Figma we have a donut chart, essentially a pie chart with the center cut out. 

This ticket is to investigate the options we have to implement this in our Rails app. No code required.

Off the top of my head, I am thinking we could use Chartkick gem to creat the pie chart, then use some custom CSS to overlay a white circle to create the donut look. But, perhaps there are other options?

This image is from the [Figma file](https://www.figma.com/file/0jVgYASUJy0KiX3BVc3dFM/Tasks?type=design&node-id=112%3A296&mode=design&t=xLo5quqgUmN5cwKS-1) > Dashboard section
<img width="127" alt="image" src="https://github.com/rubyforgood/pet-rescue/assets/95949082/6c747f71-c1be-4468-b69b-aeb7caf750ad">

**Comment by mononoken** [comment]
It sounded like in the meeting we aren't considering this design anymore. Is that correct and we can close this @kasugaijin ?

**Comment by kasugaijin** [comment]
Yes I think we can go with a simpler design approach for now @mononoken
