### ISSUE TITLE
Org Page Content Epic: As staff I can upload a Hero Image and up to two About Us images

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#592]
Currently blocked by https://github.com/rubyforgood/pet-rescue/issues/480

As staff, you can go to the dashboard and see the Page Text navbar option, where you can update the Hero Text and About Us text. This also needs to allow staff to update their Hero Image (1 image) and About Us Images (1 or 2 images) on the org's root/home page.

Implementation Criteria:
- Use the PageText model for the attachments: `has_one_attached :hero_image`and `has_many_attached :about_us_image`
- On the PageText form add attachment inputs, clearly labelled. One for Hero Image (allows one attachment), One for About Us images (allows one or two attachments). 
- Add model validations to ensure the files are images, not massive (see the Pets Controller for example)
- Add controller actions on PageTextsController for each type of attachment to attach (can use existing attachments controller for purge)
- Staff should be able to upload and purge (delete) an image. 
- Resuse partials where it makes sense e.g., the upload input, and the table to show the uploaded images (see the partials used in the Pet tabs for photos and files)
- Add permissions to the policy (may not be needed based on what is added in https://github.com/rubyforgood/pet-rescue/issues/480).
- On org root/home, render the Org.page_text.hero_image if it exists, and render either one or both About Us images, if they exist. If there is only one image, then use an existing default image for the second.
- Tests 

As next steps (different issue) we will want to look into recommending image dimensions and handling resizing of image variants. Feel free to include in this issue if you want to.

I may have forgotten something here - hit me up in Slack!

**Comment by ErinClaudio** [comment]
Can I give this one a crack? @kasugaijin 
If yes I would like to write a breakdown of my path forward before beginning any coding.

**Comment by kasugaijin** [comment]
@ErinClaudio yes sounds good!

**Comment by ErinClaudio** [comment]
@kasugaijin 

For clarification, the functionality for updating the Hero Image and About Us Images should be integrated directly within the 'Page Text' navbar option, as opposed to introducing a separate button?

**Comment by ErinClaudio** [comment]
My notes the project
https://gist.github.com/ErinClaudio/393ca48b7f2a77b8d65d5ab36a7f120c

**Comment by kasugaijin** [comment]
> @kasugaijin
> 
> For clarification, the functionality for updating the Hero Image and About Us Images should be integrated directly within the 'Page Text' navbar option, as opposed to introducing a separate button?

Yes I should be able to click Page Text in the sidebar if the dashboard and then see the form to edit text and attach images.

**Comment by kasugaijin** [comment]
> My notes for the issue https://gist.github.com/ErinClaudio/393ca48b7f2a77b8d65d5ab36a7f120c

Yes looks good! You might run into questions on some details along the way so hit us up as usual! Thanks @ErinClaudio and let me know if anything is unclear before diving in so as to save you any headaches

**Comment by ErinClaudio** [comment]
@kasugaijin @mononoken @nsiwnf 
<img width="1153" alt="Screenshot 2024-04-02 at 12 14 20 PM" src="https://github.com/rubyforgood/pet-rescue/assets/20326770/df8d2f45-3849-4dab-832b-e01721923f23">

Here's my progress so far. However, I don't believe it's correct. I think one of the following approaches would be better:

1. Create a separate but similar form specifically for images to simplify the controller logic.
2. Add a second submit button within the existing form for image uploads, with differentiation handled by the controller.

I lean towards the first option but am open to either.

**Comment by ErinClaudio** [comment]
@kasugaijin 

This looks horrible. But just wanted to show progress, I have the images rendering. not correctly but I will fix that.
More work to be done. 

<img width="1403" alt="Screenshot 2024-04-03 at 2 05 35 PM" src="https://github.com/rubyforgood/pet-rescue/assets/20326770/d9b0a8d9-273c-49a7-8adc-19cc00e965e7">

**Comment by kasugaijin** [comment]
@ErinClaudio haha nice cow :)

**Comment by ErinClaudio** [comment]
@kasugaijin This issue is Mooooooooving along

**Comment by ErinClaudio** [comment]
@kasugaijin @nsiwnf @mononoken 

I could use a little feedback.


The delete button layout feels cluttered. Consider:

1. A single button to delete both image types.
2. Separate buttons for each image type, positioned at the end of their respective form fields for clarity.

<img width="1378" alt="Screenshot 2024-04-04 at 11 03 46 AM" src="https://github.com/rubyforgood/pet-rescue/assets/20326770/d4dcd21f-63e6-487a-a662-d2de369024f5">

**Comment by kasugaijin** [comment]
@ErinClaudio could we re-use the partials for image uploads and displaying the images in a table, along with a delete button, below the submit button?

![image](https://github.com/rubyforgood/pet-rescue/assets/95949082/1d00fb41-d469-49fa-b997-5a2e7b7498ed)

**Comment by ErinClaudio** [comment]
@kasugaijin 
Perfect and thanks
