### ISSUE TITLE
Adjust registration and session links in navbar

### ISSUE THREAD

**Issue by mononoken** [rubyforgood/pet-rescue#601]
Please comment if you'd like to be assigned, and let us know if you have any questions.

## Description
These are two small, separate tasks involving links in the navbar. Please fix both of these in 1 PR.
1. The mobile navbar log out button displays regardless of the users session. This should only display if a user is signed in. However, it currently shows regardless of signed in status.
2. Users have to click the log in link or scroll to the bottom of the homepage to get to the sign up link. We want to add a link next to the log in link so that users can quickly sign up.

### Mobile navbar log out button
- [ ] `Log out` is not displayed in the mobile hamburger menu when signed out (see exhibit 1)
- [ ] `Log out` is displayed in the mobile hamburger menu when signed in
### Sign up link on home page
- [ ] Sign up link displays to the left of the log in link on home page navbar
  - [ ] On desktop (see exhibit 2)
  - [ ] On mobile (see exhibit 3)
- [ ] Style of `Sign up` link matches `Log in` link
- [ ] `Sign up` link does not display when user is logged in

Exhibit 1:
![remove-log-out-as-guest](https://github.com/rubyforgood/pet-rescue/assets/81536479/c330a715-258e-44e8-ab00-a45a21bbbeb8)
Exhibit 2: 
![sign-up-root-desktop](https://github.com/rubyforgood/pet-rescue/assets/81536479/c843e8b0-84af-4a2f-8748-3583e0fbe900)
Exhibit 3:
![sign-up-root-mobile](https://github.com/rubyforgood/pet-rescue/assets/81536479/3e3b26fd-fa75-4b66-bc2f-7a248801f265)

**Comment by mehranjavid** [comment]
Hi @mononoken, Can I work on this?
