### ISSUE TITLE
As an organization Admin, I can request an organization account in the app.

### ISSUE THREAD

**Issue by Ndshah82** [rubyforgood/pet-rescue#610]
We need to add a button that allows admin users to invite staff upon request to their organization.

[Insert design here]

[Insert technical details here]

**Comment by kasugaijin** [comment]
Hey @Ndshah82 Admin can invite staff to their org in the app currently. This is based on stakeholder feedback - that they want to invite staff. It allows them more control over setting staff up, as they will end up receiving requests from random people (this happened in the original app).

**Comment by Ndshah82** [comment]
@kasugaijin I pulled it from the Miro.  It's on the staff board, so I was under the assumption that it was for staff to invite users.  I updated the issue per your comments.  If further clarification is required, please provide.

**Comment by kasugaijin** [comment]
Ah yes that’s a bit confusing it’s on the staff panel but the column is for organization. We could actually benefit from an organization panel couldn’t we! Thanks for updating.

**Comment by kasugaijin** [comment]
Will re-write so there is less discussion clutter.
