### ISSUE TITLE
Scope organization specific controllers under organization

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#621]
We set the tenant in `app/controllers/organizations/base_controller.rb` using `OrganizationScopable`. The controllers scoped under `controllers/organizations` inherit from `Organizations::BaseController`. This means the logic in these controllers is executed in the tenant scope, e.g., calling `Task.all` will return all tasks for current organization only. This helps to keep data secure between organizations.

We have some routes/controllers that are used to create common Organization workflows, but they are not currently scoped under Organization. This is not ideal because it means that calling resources in these controllers could return all records from all organizations (e.g., `Task.all` will return all tasks from all orgs), presenting a risk of data bleeding. So, we need to move these routes, controllers under the organization scope. 

Acceptance criteria:
- move the list of controllers and associated routes (not crossed out) below into `controllers/organizations` and inherit from `Organizations::BaseController` instead of `ApplicationController`
- Rename the classes appropriately for their new scope
- Fix tests (renaming)
![image](https://github.com/rubyforgood/pet-rescue/assets/95949082/9b9c97ea-cc4a-4aa6-9c93-9199c555e01e)

**Comment by jmilljr24** [comment]
I'd like to work on this.

**Comment by kasugaijin** [comment]
All yours @jmilljr24
