### ISSUE TITLE
Refactor top navbar

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#622]
Remove avatar
Put relevant dropdown links (dashboard, sign out) in navbar as nav link

**Comment by mehranjavid** [comment]
Hi @kasugaijin, Can i work on this issue?

**Comment by mononoken** [comment]
Not sure if this would fall under the scope of this PR. However, I noticed today that if you are logged in as an adopter, the `Adopt` link in the navbar (which sends to user sign up form) results in an `ArgumentError`.

I feel like this link should change its path to the adoptable pets index when the user is already signed in.

We should probably add some authorization logic to prevent authenticated users from going to sign_up form (and probably sign_in) if it's going to raise an error too. I can create a separate issue for that if you agree.

**Comment by kasugaijin** [comment]
Thanks @mononoken let’s keep that in this issue! I agree on your suggestions.
