### ISSUE TITLE
Tenant Footer: Change text and add link to the application root

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#623]
We want people browsing an org (tenant) site, who can see the tenant footer, to know that this website is provided by Pet Rescue application, and that they can also get a website just like it, and be able to click a link to go to the application root page

![image](https://github.com/rubyforgood/pet-rescue/assets/95949082/a5edda9c-340b-451d-8300-e285aeb1bfde)

Acceptance Criteria
- change `We provide a platform for Pet Rescues and Animal Service Organizations` to something like `If you are a pet adoption or foster organization and want a website like this one, for free, click here.` The click here should be a link to the organization root i.e., `petrescue.com`.

**Comment by Gabe-Torres** [comment]
Can I be assigned this issue? 🐶

**Comment by kasugaijin** [comment]
@Gabe-Torres @jeevikasirwani made a pull request for this issue so it’s already been spoken for (I could add them on this issue as assigned, sorry for that). We will have more good first issues coming up soon!

**Comment by Gabe-Torres** [comment]
Gotcha, No problem! Thank you
