### ISSUE TITLE
Organization Profile: As staff I can save URLs on my organization profile. 

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#633]
Organizations will benefit from being able to save URLs on their profile for things like social media and donation links. This issue is to enable this to happen. 

Acceptance Criteria:
- Migration on the organizations table to remove the about_us column, and to add three new text columns for facebook_url, instagram_url, donation_url. I did consider using string datatype, but by default is limited to 255 chars, and the jury seems to be out on the best datatype, I say text just because we can accept longer URLs if required. But, open to your ideas.
- Add the new URL input fields on the Organization Profile form. 
- On the organization profile model, add a URL validation for each attribute to make sure it is a valid URL being saved. Do not allow save if not a valid URL. 
- I should be able to add URLs in the UI, then retrieve them in the console from the OrganizationProfile as a dev.

**Comment by MooseCowBear** [comment]
I'd like to work on this. Do we know how we want to go about validating urls? If not, I can look into options.

**Comment by kasugaijin** [comment]
@MooseCowBear all yours. I think Rails 7 has a built in module for validating URLs. Or we can write a custom validator class, but I don't think we need to.
