### ISSUE TITLE
Foster Epic: Add columns to the Matches table so it can handle adoptions and fosters

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#643]
We need a Match to be able to handle both adoptions and fosters. Adoptions are final, whereas fosters have a start and end date. 

Acceptance criteria:
Migration to add columns on matches table:
- match_type, string, null false, use an enum on the model for `adoption` or `foster`
- start_date, datetime
- end_date, datetime

- you will need to update tests and seeds (just focus on getting adoptions to work, no need to add any fosters)

**Comment by jmilljr24** [comment]
I'd like to work on this.
