### ISSUE TITLE
Staff Pet Index: Implement pagination

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#644]
As a staff I can click through the paginated dataset of pets within the pets index table. This will be implemented using the Pagy gem https://github.com/ddnexus/pagy

Acceptance criteria
- Add seeds to create 50 pets in total
- Each page contains up to 10 pets
- I can click to navigate from page to page using 
![image](https://github.com/rubyforgood/pet-rescue/assets/95949082/0868d3d5-af80-4b7e-bc3c-7cef9610bb29)

**Comment by gdomingu** [comment]
Can I be assigned to this? Interested in doing it.
