### ISSUE TITLE
Foster index and creation form

### ISSUE THREAD

**Issue by mononoken** [rubyforgood/pet-rescue#645]
This work likely needs design tweaks but the implementation can certainly be built right now.

## Description
We want to have an index page for showing a list of all created fosters for the active organization. This page will be meant for staff use. The page should be able to also create new fosters by inputting into a form. In the future, it should be filterable/sortable.

### Data Vocab (refer if you have any confusion)
- `Foster` - caretaking for a pet for a duration of time (contrasted with adoption where there is no end time)
- `Fosterer` - person who fosters
- `Adopter` - person who adopts a pet (note: in the app, it is possible for a user to be both an `adopter` and a `fosterer`)
- `Match` - adoption or foster

## For Design
Design work completed: 
https://www.figma.com/file/0jVgYASUJy0KiX3BVc3dFM/Tasks?type=design&node-id=645-2&mode=dev

> The Pet Task index page can be used as a reference (Task V2 Completed in Figma):
> <img width="722" alt="image" src="https://github.com/rubyforgood/pet-rescue/assets/81536479/37154f49-0084-4942-bbe4-52460e39117f">
> - We do not need the checkboxes, descriptions, or "Show Completed" toggle
> - We do need: (for each entry)
>   - Fosterer name
>   - Pet name
>   - Start date of foster
>   - End date of foster
>   - Edit button
>   - Delete button
>   - Thought: Maybe the delete button should only appear when activating the Edit button to conserve space for mobile
> - We also need a button at the top, like tasks, to open a form for making new fosters
> - We want the mobile view to work as well.

## Acceptance Criteria
- [x] Show all `Match` records with match_type of `:foster`
  - [x] Matches will be grouped by Pet in the index per design direction
  - [x] `Match` records should be scoped for the organization (this most likely is already handled by ActsAsTenant)
  - [x] Default sort? Created at recency? Maybe touch Pet via match updates and sort by last updated pets.
- [x] Index should include the following info:
  - [x] Fosterer name
  - [x] Pet name
  - [x] Start date
  - [x] End date
  - [x] Link for editing individual fosters (should utilize Turbo)
  - [x] Button for destroying the individual foster
~~- [ ] Utilize Turbo to instantiate new `Foster` form~~ (We decided in meeting that this won't be necessary for now)

**Comment by kasugaijin** [comment]
@mononoken the blocking task is up for PR so this should be unblocked soon. Do you think we can get this to a point where it can be assigned to a GitHubber (if they are interested) without design work? I can help facilitate explanation of this ticket with a Loom video. I think we could do a reasonable job and get a good first pass implementation up (that may need only some design tweaks afterwards).

**Comment by mononoken** [comment]
Perfect @kasugaijin ! Thanks for adding the loom. I will mark this ready. If we want additional design for this, we can make those design changes later like we discussed in the last meeting.

**Comment by kasugaijin** [comment]
@mononoken Are we ready to add design to this issue and remove the Needs Design label? 🌜

**Comment by mononoken** [comment]
> @mononoken Are we ready to add design to this issue and remove the Needs Design label? 🌜

@kasugaijin I think so! Kirin is out of town this week, but the figma file looks ready. I will add a link to the file to the issue now.
