### ISSUE TITLE
Fix: Pet settings dropdown on staff "Pets" page are cut off when only one pet is displayed

### ISSUE THREAD

**Issue by jmilljr24** [rubyforgood/pet-rescue#672]
When only one pet is shown on the table, the setting's dropdown is cut off at the bottom so not all of the options are displayed.

The settings dropdown should display the same as when multiple pet's are in the table.

**Fix**
![Screenshot from 2024-04-26 16-26-07](https://github.com/rubyforgood/pet-rescue/assets/16829344/d6d6d021-de1e-45fb-a0c0-312216388ffb)

**Correct**
![Screenshot from 2024-04-26 16-27-25](https://github.com/rubyforgood/pet-rescue/assets/16829344/7625424c-6225-4977-b733-251a12e19907)

**Comment by OliverLeighC** [comment]
Could I work on this?

**Comment by jmilljr24** [comment]
@OliverLeighC All yours! Let me know if you have any questions.

**Comment by OliverLeighC** [comment]
Looks like it's "expected behavior" for responsive tables 
https://github.com/tabler/tabler/issues/1343#issuecomment-1308569481

but I am going to see if I can get the suggested popper config fix to work

**Comment by OliverLeighC** [comment]
Hmm... setting popper config to {strategy: "fixed"} reveals the full menu but doesn't behave nicely when scrolling 

https://github.com/rubyforgood/pet-rescue/assets/51760107/571bbcfc-206a-454f-a411-786570443ce5

Will keep investigating

**Comment by jmilljr24** [comment]
> Hmm... setting popper config to {strategy: "fixed"} reveals the full menu but doesn't behave nicely when scrolling
> Clip.mov
> 
> Will keep investigating

I really appreciate you playing around with this. If none of the suggestions that you linked to give good results or if there will be some compromises, post an update and the team can discuss it.

**Comment by jmilljr24** [comment]
@OliverLeighC Setting a  mini-height of the table might be the easiest option. The dropdown doesn't have a lot cut off so it might work out ok to set a min-height and adjust table headers to fit. But whatever works best!

**Comment by OliverLeighC** [comment]
here is what it looks like with the min-height: 
<img width="1525" alt="image" src="https://github.com/rubyforgood/pet-rescue/assets/51760107/ec7cd3a7-a004-4311-afc9-087defc86325">
<img width="1534" alt="image" src="https://github.com/rubyforgood/pet-rescue/assets/51760107/092442f9-3bcf-4a0b-bcc5-bd63512f8c62">

more rows for comparison: 
<img width="1540" alt="image" src="https://github.com/rubyforgood/pet-rescue/assets/51760107/572332b9-f622-4803-8e6a-83387e33f100">
<img width="1519" alt="image" src="https://github.com/rubyforgood/pet-rescue/assets/51760107/9bb93ce6-a146-4153-9c4b-912691d24862">

I think it looks okay, will submit my PR but let me know if it needs tweaking
