### ISSUE TITLE
Rename foster_application_reviews to manage_fosters

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#678]
We currently have a route, controller, and views for `foster_application_reviews`. This naming is not accurate and needs to be changed to `manage_fosters`

Acceptance Criteria: 
- change route, controller, view
- update tests so they pass

**Comment by LindseyB** [comment]
Can you assign this to me?

**Comment by kasugaijin** [comment]
Done @LindseyB
