### ISSUE TITLE
PageTexts: Find out why hero and about us sections not showing PageText data

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#682]
This PR https://github.com/rubyforgood/pet-rescue/pull/618 enabled orgs to add Hero images and About Us images that would be displayed on the org root page if added. On the production site https://pet-rescue-f6df7ce0e850.herokuapp.com this works for Alta, but not Baja. Why?

**Comment by jmilljr24** [comment]
This might have something to do with the seed files. `02_baja` has `PageText.create!(hero: nil, about: nil)` and `01_alta` does not. They both create the PageText(with values) when the org is created so baja ends up have two PageTexts. 

I can't seem to produce the issue locally but it would make sense that the conditionals in `home/index` view are false if the `Current.organization.page_text` being checked has the nil values.

Could you try deleting the nil pagetext from the rails console on heroku and see if that fixes it? Or would it be easier to push up a change and reset the db?

**Comment by kasugaijin** [comment]
Good catch! That looks like a likely culprit @jmilljr24 
I think we should push an update of the seed file. I think every successful deploy to heroku will rerun bin/setup so it should re-seed. If not, we can do that after. Did you want to make a PR with that seed file change?
