### ISSUE TITLE
Views: Clean up and update names

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#688]
Our Views could do with a bit of a cleanup. Some view directories/files are not even in use and can be deleted e.g., `organizations/settings` and naming of some components and partials can be updated to reflect the new namespacing i.e. rename `dashboard` to `staff_dashboard`. I also think there are some components and/or partials not in use e.g., One of the dashboard navbars. 

This issue is to go through the views to find cases that can be deleted (not in use) and renamed to better match the new namespaces of `staff` and `adopter_fosterer`.

**Comment by LindseyB** [comment]
Can you assign this to me?

**Comment by LindseyB** [comment]
I ran the following to start to wrap my head around what needed to actually be changed here. 

```
@LindseyB ➜ /workspaces/pet-rescue (remove-unused-views) $ discover-unused-partials .
The following partials are not referenced directly by any code:
  app/views/components/_avatar.html.erb
  app/views/components/_xl_avatar.html.erb
  app/views/components/adopter_foster_dashboard/_nav_tab.html.erb
  app/views/organizations/staff/dashboard/_navbar.html.erb
  app/views/organizations/staff/manage_fosters/_search_results.html.erb
  app/views/organizations/staff/pets/tabs/_files.html.erb
  app/views/organizations/staff/pets/tabs/_overview.html.erb
  app/views/organizations/staff/pets/tabs/_photos.html.erb

  The following partials are only referenced directly by the partials above:
    app/views/components/_attachment_form.html.erb
    app/views/components/_file_attachment_table.html.erb


Some of the partials above (at any level) might be referenced dynamically by the following lines of code:
  app/views/organizations/staff/pets/show.html.erb:<%= render partial: "organizations/staff/pets/tabs/#{@active_tab}", locals: { applications: @pet.adopter_applications, pet: @pet} %>
  app/views/static_pages/donate.html.erb:}).render('#paypal-donate-button-container');
```

Things that appear safe to remove: 

- [ ] `app/views/organizations/settings.html.erb`
- [ ] `app/views/organizations/staff/dashboard/_navbar.html.erb`

> naming of some components and partials can be updated to reflect the new namespacing i.e. rename `dashboard` to `staff_dashboard`

I think from what I'm seeing now the views are in `app/views/organizations/staff/dashboard` which seems to match what I am seeing in the controllers `app/controllers/organizations/staff/dashboard_controller.rb` and the class `Organizations::Staff::DashboardController` 

While I'm in here making these changes is what is outlined above sound good or are there other pieces I need to make sure I remove or adjust?

**Comment by kasugaijin** [comment]
Hey @LindseyB tha is for taking it in. Could you make a PR instead? Just easier to pull down and look at. From the above I agree those two listed under things safe to remove make sense. I’d also just double check each time you delete something to check in the browser that things still work (you’re probably already doing that but just to make sure. Not all of this would be covered by tests to a manual check is good).
