### ISSUE TITLE
Raise an error if a developer tries to use the #new action in the invitations controller

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#695]
The `Staff::InvitationsController` #new action is not to be used because we have separate controllers to handle this for each resource that is receiving an invite. We currently block use using authorization, but, this is not really authorization related, as we want to prevent developer from using this route. 

Instead, the method should raise an error to tell developers not to use the action:

`raise NotImplementedError, "Do not use the 'new' action in Staff::InvitationsController."`

Acceptance criteria:
- add a test to ensure the error is raise when hitting that controller action

**Comment by sarvaiyanidhi** [comment]
Hi @kasugaijin,

I would like to take up this issue. Can you please assign it to me? Thanks

**Comment by kasugaijin** [comment]
All yours @sarvaiyanidhi
