### ISSUE TITLE
Bug: fix path helper method name

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#700]
Currently in `Organizations::Staff::PageTextsController` in the update action, if @page_text does not update we redirect to `edit_page_text_path`, this causes an error, it needs to be `edit_staff_page_text_path`

<img width="1389" alt="image" src="https://github.com/rubyforgood/pet-rescue/assets/95949082/7fa8b6e8-fdf8-4d84-a31d-04b873395da3">

To reproduce, upload two About Us images, and save. Then try to upload a third image and save. You will get an error. 
Expected behaviour, on attempt of uploading a third image you should get an alert message saying only 2 images allowed.

**Comment by Hassaan68** [comment]
@kasugaijin , can you please assign this one to me?

**Comment by jmilljr24** [comment]
@Hassaan68 all yours!

**Comment by Hassaan68** [comment]
@jmilljr24 fixed and tested
