### ISSUE TITLE
Page Text Images: Investigate the best way to maintain aspect ratios on About Us images

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#701]
We have the Page Text resource that allows org staff to upload a hero image and two About Us images that are displayed on the org's root page. Currently, if you upload two About Us images of different aspect ratios, they will not render in the same dimensions on the org root page. For example, below. 
<img width="1387" alt="image" src="https://github.com/rubyforgood/pet-rescue/assets/95949082/feaa7f9d-a3e4-40d8-8873-92021140dd99">

If both images are the same aspect ratio, they both show as the same size: 
<img width="1388" alt="image" src="https://github.com/rubyforgood/pet-rescue/assets/95949082/1ffe47cc-053c-4a42-8683-07b7733a8529">

Investigate an appropriate way to manage the aspect ratios of uploaded images. If we don't have to use a gem, great. But we can use a gem if there are no other options. 

Acceptance criteria:
- staff can upload images without worrying about aspect ratios and both images appear the same size on the org root page. 
- No need for tests

**Comment by Hassaan68** [comment]
@kasugaijin , what are the steps to reproduce this one? In local environment the About page is quite different

**Comment by kasugaijin** [comment]
@Hassaan68 so this is on the Org's home page, there is an about us section. You can ignore `/about_us` page. 

Log in as a staff, go to the dashboard, go to Page Texts, make some changes and upload images, save, then go back to that Org's home page and scroll the About Us section. 

Let me know if you have more questions!

**Comment by jmilljr24** [comment]
I think the simplest solution would be to use bootstrap [ratio](https://getbootstrap.com/docs/5.3/helpers/ratio/#about) and style: "object-fit: cover;" so the image fills the space. 

I pushed a branch up if you want to play around with it. Not sure if this what you had it mind.
https://github.com/rubyforgood/pet-rescue/tree/jmilljr24/investigate-image-aspect-ratios

![Screenshot from 2024-05-17 18-13-25](https://github.com/rubyforgood/pet-rescue/assets/16829344/6c06f8d9-09f7-43fb-a2dc-486c84306e12)

![Screenshot from 2024-05-17 18-13-05](https://github.com/rubyforgood/pet-rescue/assets/16829344/0ff29d47-2bd8-40c1-86de-170d4db4a659)

**Comment by kasugaijin** [comment]
Awesome thanks @jmilljr24 i will test it out. I think CSS should be all we need!

**Comment by kasugaijin** [comment]
The aspect ratios are not actually maintained (they get cropped which might be annoying if you don't have a lot of room around the focal point of the image), but the images end up the same size, which is better than current. I prefer keeping it simple for now and not adding more gems that we need. So, let's roll with this, and if we hear frustration with this from user feedback we can fix it. Can you please make a PR if you agree?

**Comment by jmilljr24** [comment]
I can make a PR for this. I think it's a good baseline to at least keep the layout from looking odd. Worst case staff will have to try a couple different photos to see what looks best.

Maybe we can talk a little more about it at the next meeting. I started typing an essay but it would be easier to talk about.

**Comment by kasugaijin** [comment]
@jmilljr24 agreed! Sounds good.
