### ISSUE TITLE
Bug: Fix duplicate year in org footer

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#703]
On the org scoped pages there is a footer, in the bottom left we display the year, and it is being rendered twice. Please fix.
<img width="408" alt="image" src="https://github.com/rubyforgood/pet-rescue/assets/95949082/6cc302ed-5d69-420d-a468-6fee769fef0e">

**Comment by Hassaan68** [comment]
hi @kasugaijin , can you please assign this one to me ?

**Comment by jmilljr24** [comment]
@Hassaan68 Assigned! Thank you

**Comment by Hassaan68** [comment]
hi @jmilljr24 , I am not able to reproduce this one on my side. are there any steps to reproduce it?

**Comment by kasugaijin** [comment]
Huh that is weird! I cannot reproduce it locally either. That screenshot was from the production site https://pet-rescue-f6df7ce0e850.herokuapp.com/ but it also is not occurring now. I think we can close this issue. Thank you for looking into iT @Hassaan68

**Comment by Hassaan68** [comment]
Thanks @kasugaijin
