### ISSUE TITLE
Adoption Applications: Add pagination.

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#706]
We added pagination to `/staff/pets` and now we should add it to `/staff/adoption_application_reviews`.

I think that 5 per page would be good? Open to other ideas here as well. 

Refer to this PR for how it was done on staff pet index: https://github.com/rubyforgood/pet-rescue/pull/649

Acceptance criteria:
- Adoption application review page shows paginated cards, 5 per page
- No need to add to seed files as we have enough for more than one page already
- No need for test

**Comment by atbalaji** [comment]
@kasugaijin I would love to work on this issue

**Comment by kasugaijin** [comment]
@atbalaji all yours! No rush! Thank you

**Comment by atbalaji** [comment]
/staff/adoption_application_reviews in this page i am getting errors due to existence of adopter_foster_accounts with no adopter_foster_profile in pre populated data. I want to know your thoughts on handling this?

**Comment by kasugaijin** [comment]
> __/staff/adoption_application_reviews_ in this page i am getting errors due to existence of adopter_foster_accounts with no adopter_foster_profile in pre populated data. I want to know your thoughts on handling this?

You are working off the latest main branch, right?

**Comment by atbalaji** [comment]
Can we close this issue?
