### ISSUE TITLE
Staff Pets Index: Remove unnecessary columns from the table

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#712]
UI change: we do not need these columns in the staff Pet index table. Please remove them.

![image](https://github.com/rubyforgood/pet-rescue/assets/95949082/013e0c8c-af34-4efb-9c17-f903b062bc8a)

**Comment by atbalaji** [comment]
Hi @kasugaijin , I would love to work on this. I have raised PR for the earlier issue. Since we are removing sex, breed and weight columns from UI should we remove sex filter as well?

**Comment by kasugaijin** [comment]
@atbalaji sounds good! You raise a very good point! I think more about this and we should keep the sex column and filter but get rid of the others. Reason is because we could have two pets with the same name so sex might be a useful attribute to filter on also.
