### ISSUE TITLE
PageTexts: Enable staff to customize the text shown to the right of an adoptable dog

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#718]
On the adoptable dog show page we have this box of info to the right, this is important details that an org wants to get across to someone considering adopting. We should enable staff to customize this. 

![image](https://github.com/rubyforgood/pet-rescue/assets/95949082/f4930a74-e477-4148-9fbd-f3a287396d83)

We want to add a new column on the page texts table called `adoptable_pet_info`, `text`, and add this as a text area input to the page texts form under a new H3 heading Adoptable Pet Information.

In the UI for the adoptable pet show page, we want to keep the sentence referring to the FAQ at all times. If there is a `pagetext.adoptable_pet_info` then we want to show a heading called Important Information, and render the text provided. We can delete the rest of the current text in the view for this page.

**Comment by MooseCowBear** [comment]
I'd like to work on this
