### ISSUE TITLE
Fix User tables db schema

### ISSUE THREAD

**Issue by Thrillberg** [rubyforgood/pet-rescue#72]
We want `users` to have only `email` and `password` (as in Devise) and put other fields (names) on a `persons` table. Other fields (currently on profile) will later get moved out of person record onto some sort of form response table.

Also have a `roles` or `positions` table associated to a `person`, in which we store staff vs adopter etc.

**Comment by jadekstewart3** [comment]
@jadekstewart3 rename adoption to be match
