### ISSUE TITLE
Static pages: remove the partners and about us pages

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#726]
Delete the routes, controller actions and views (and any applicable tests) for About Us and Partners pages as they are not required.

**Comment by LindseyB** [comment]
Can you assign this to me?

**Comment by kasugaijin** [comment]
@LindseyB done

**Comment by LindseyB** [comment]
These pages are linked from the home and also the tenanted home, do we just want to remove those pages from the non-tenanted? or both? 

http://localhost:3000/about_us vs http://localhost:3000/alta/about_us or should all be removed?

**Comment by kasugaijin** [comment]
Ah good question. Let’s leave the about us and partners pages for the root org. Just remove for the orgs.
