### ISSUE TITLE
new form-related tables

### ISSUE THREAD

**Issue by Thrillberg** [rubyforgood/pet-rescue#74]
`submission_templates`
`questions`
`submission_template_questions` (join table)

for orgs building their own forms

rename `application` to `submission` (application is a reserved word) https://github.com/rubyforgood/pet-rescue/issues/75

**Comment by aileenchoi** [comment]
Hi @Thrillberg, is this the same as[ issue 76](https://github.com/rubyforgood/pet-rescue/issues/76)?
