### ISSUE TITLE
Check and fix all test assertion order

### ISSUE THREAD

**Issue by mononoken** [rubyforgood/pet-rescue#744]
## Description
I just noticed I wrote all the policy test assertion arguments in the wrong order. Woops!
```ruby
    context "#manage?" do
        ...
        should "return false" do
          assert_equal @action.call, false
        end
    end
```
It should be:
```ruby
          assert_equal false, @action.call
```
From minitest docs:
```ruby
  def i_can_has_cheezburger?
    "OHAI!"
  end
...
  def test_that_kitty_can_eat
    assert_equal "OHAI!", @meme.i_can_has_cheezburger?
  end
```

I copied this ordering from existing tests in the app, so I suspect many other tests also have this backwards. Actually, at a quick skim, I didn't see any tests with the correct order in our test suite. I suspect this is from familiarity with spec `expect` style testing.

This shouldn't affect passing test results given the nature of comparison, but it does make the failure results confusing.

We should check all tests. Our test suite is not monstrous, so I think this could be handled in one issue, but if we want to separate the work out, we could make separate ones for each test type.

## Acceptance Criteria
- [x] Check and fix the `assert` method argument order for:
  - [x] controller tests
  - [x] helpers tests
  - [x] integration tests
  - [x] mailer tests
  - [x] models tests
  - [x] policies tests
  - [x] services tests
  - [x] shared tests
  - [x] support tests
  - [x] system tests

**Comment by jaxonavena** [comment]
@Tacabr0n put his blood, sweat, and tears into this grind
