### ISSUE TITLE
Authentication: Move the authenticate_user! method to application controller

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#745]
We call the `authenticate_user!` in three controllers right now, but ideally we always call this method to ensure the user is authenticated on routes that should be authenticated. Seeing as we have more routes that require authenticateion than not, it makes sense to move the method to `ApplicationController`, and then explicitly skip this check in controllers that are public (do not require authentication). 

We can skip this check in these controllers:
- static pages
- errors
- contacts
- organizations - home
- organizations - FAQ
- organizations - adoptable pets

Double check - I may have missed one :)

**Comment by Gabe-Torres** [comment]
Hey, I'll take this one! 🐶
