### ISSUE TITLE
Add foster email flow

### ISSUE THREAD

**Issue by mononoken** [rubyforgood/pet-rescue#751]
## Description

Right now, creating a foster results in the fosterer receiving the same email as if an adoption was created. This is because the email is sent via a callback in the `Match` model and fosters and adoptions are both types of `Matches`.

We want to send a different email to fosterers when they have been assigned a foster pet. 

It would also be good to remove the callback first during this task and move the sending of the email to the controller. This email in the callback muddles up the testing environment.

## Acceptance criteria
- [ ] Remove `  after_create_commit :send_reminder` from `Match`
- [ ] Change `MatchMailer` to `AdoptionMailer`
- [ ] Rename related view files for new mailer name
- [ ] Send `AdoptionMailer` method in `Organizations::Staff::MatchesController#create`
- [ ] Create `FosterMailer`
- [ ] Send `FosterMailer` method in `Organizations::Staff::ManageFostersController#create`
- [ ] Create new FosterMailer email views

The content of the foster email can look something like this:

> We are thrilled to inform you that you have been assigned a new foster pet! Thank you for opening your heart and home to <%= @pet.name %>. Your dedication and support make a significant difference in the lives of the animals we care for.

**Comment by Naraveni** [comment]
Could you please assign this to me , I would like to try this.

**Comment by jaxonavena** [comment]
@Naraveni I got you
