### ISSUE TITLE
Add validation for changing pet's placement type

### ISSUE THREAD

**Issue by mononoken** [rubyforgood/pet-rescue#752]
## Description
Pets can have their attributes edited at `/staff/pets/:id/edit`

We want to add a validation to prevent the pet's `placement_type` from being changed to one that conflicts with their current foster `Match`. If a pet is currently being fostered (which means they have an active or upcoming `Match` with `match_type: "foster"`), we want a validation to prevent the `placement_type` from being changed to only `"Adoptable"`.

Note, the validation should not prevent a `Pet` that has a completed foster from having its `placement_type` changed. We only care about fosters that have `end_dates` after the current time. 

## Acceptance criteria
- [ ] Add described validation to `Pet` model
- [ ] Add unit test for validation

**Comment by MooseCowBear** [comment]
I can work on this

**Comment by jmilljr24** [comment]
@MooseCowBear Thank you!!
