### ISSUE TITLE
Adopter Applications: Enable an adopter to remove a withdrawn application from their dashboard view

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#757]
Currently, adopters can see their adopter applications in their dashboard, but they have no way to remove them. So, we need to be able to allow adopters to remove/delete applications from their view if they are withdrawn. 

Acceptance Criteria: 
- If the status of the application is `withdrawn` show the delete button on the application row
- When the user clicks the delete button, set the 'profile_show' attribute to false. I think the existing update action on the adopter applications controller will do this.
- This page uses broadcast to live update the collection after changes. As such, the collection should live update and remove the row after clicking delete.
- The index collection for the adopter applications should not show any where `profile_show` is false.

View
![image](https://github.com/rubyforgood/pet-rescue/assets/95949082/48d65e46-6537-4612-afc9-a6c8fa71aa08)

Use this delete button
![image](https://github.com/rubyforgood/pet-rescue/assets/95949082/da668215-8dba-4ba8-b55f-9d617316513d)

**Comment by jameybash** [comment]
hi can i try this one???
