### ISSUE TITLE
Dashboard shows application count and link

### ISSUE THREAD

**Issue by mononoken** [rubyforgood/pet-rescue#770]
## Description

Let's complete the application card with some functionality. The card exists on the dashboard view already. Let's show the user's application count there and make the card a link to `alta/adopter_fosterer/applications` to show the user's applications.

<img width="1152" alt="image" src="https://github.com/rubyforgood/pet-rescue/assets/81536479/a0ee395c-5b74-4daf-af87-03a4c476b26b">

## Acceptance Criteria
- [ ] Dashboard application card shows AdopterApplication count for user
- [ ] Card links to applications index

**Comment by ErinClaudio** [comment]
@mononoken I would like to take this one, please.
