### ISSUE TITLE
System tests in CI test-suite run excluded

### ISSUE THREAD

**Issue by edwinthinks** [rubyforgood/pet-rescue#8]
I noticed that in our GitHub actions workflow file [here](https://github.com/rubyforgood/pet-rescue/blob/main/.github/workflows/rubyonrails.yml#L43) is not running the system tests. To run these system tests you have to specify to include them or run them seperately via `rails test:system`. Whereas, `rails test` just runs the non-system test suite.

**Comment by Thrillberg** [comment]
Thanks for catching that, @edwinthinks! Yes, I think we want to run all tests.

**Comment by Thrillberg** [comment]
I believe this is resolved by [this commit.](https://github.com/rubyforgood/pet-rescue/pull/70)
