### ISSUE TITLE
PageText: Rename this resource to CustomPage

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#819]
The PageText name was outgrown very quickly and not that intuitive. So, let's rename this resource CustomPage. This means renaming all areas in the app (table, model, controller, policies, views, tests etc.). It should be a relatively straightforward find and replace.

Any questions - comment below!

Acceptance Criteria:
- renaming of the PageText resource to CustomPage
- As staff, when looking at the dashboard, the navbar link says Custom Pages instead of Page Text

**Comment by Jayesh-69** [comment]
Hie, let me try this

**Comment by Trevor-Robinson** [comment]
I would like to take this issue.

**Comment by kasugaijin** [comment]
How's this going @Trevor-Robinson? I will unassign unless you are still planning to work on it!

**Comment by Trevor-Robinson** [comment]
Sorry for the delay. Hoping to have this done today.
