### ISSUE TITLE
Pet Task: Add recurring icon and label to tasks

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#820]
Add the recurring label to Pet Tasks per the design below. Use the Geeks theme icon for 'Social Profiles' here: https://geeksui.codescandy.com/geeks/pages/dashboard-instructor.html

![image](https://github.com/rubyforgood/pet-rescue/assets/95949082/f0f62cf6-967a-4fed-ae32-ca49b30f9e53)

**Comment by wandergithub** [comment]
Can I take it?

**Comment by kasugaijin** [comment]
@wandergithub all yours

**Comment by wandergithub** [comment]
this can be closed.
