### ISSUE TITLE
Rename AdopterApplication to CustomForm::Submission

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#823]
AdoptionApplication should be renamed to CustomForm::Submission. This means renaming all areas in the app (table (submissions), model, controller, policies, views, tests etc.). It should be a relatively straightforward find and replace.

Note the table should be renamed to `submissions_table`. The CustomForm scope helps to organize this resource along with others that are similar.

Any questions - comment below!

**Comment by MooseCowBear** [comment]
I can do this

**Comment by MooseCowBear** [comment]
@kasugaijin Should the methods with 'application' in their names also be renamed? What about all the variables? And the AdoptionApplicationReviewsController?

**Comment by kasugaijin** [comment]
@MooseCowBear yes ideally we replace all for consistency. I think search and replace should make this pretty straightforward!

**Comment by kasugaijin** [comment]
@MooseCowBear please nest the classes instead of inline: https://thoughtbot.com/blog/why-you-should-nest-modules-in-ruby we are trying to move to the nested format throughout.
