### ISSUE TITLE
Refactor Answer to CustomForm::SubmittedAnswer

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#833]
Answer should be renamed to CustomForm::SubmittedAnswer. This means renaming all areas in the app (table (answers), model, controller, policies, views, tests, variables, methods etc.). It should be a relatively straightforward find and replace.

Note the table should be renamed to submitted_answers_table. The CustomForm scope helps to organize this resource along with others that are similar.

please nest the classes instead of inline: https://thoughtbot.com/blog/why-you-should-nest-modules-in-ruby we are trying to move to the nested format throughout.

Any questions - comment below!

**Comment by sarvaiyanidhi** [comment]
Hi @kasugaijin I can take up this issue. Can you please assign it to me? Thanks

**Comment by sarvaiyanidhi** [comment]
Hi @kasugaijin ,

I see that you have mentioned above to rename model Answer to CustomForm::Answer but you have mentioned table to be renamed from answers_table to submitted_answers_table so just want to confirm we don't want to name model as CustomForm::SubmittedAnswer to follow standard with table name?

Thanks,
Nidhi

**Comment by sarvaiyanidhi** [comment]
> Hi @kasugaijin ,
> 
> I see that you have mentioned above to rename model Answer to CustomForm::Answer but you have mentioned table to be renamed from answers_table to submitted_answers_table so just want to confirm we don't want to name model as CustomForm::SubmittedAnswer to follow standard with table name?
> 
> Thanks, Nidhi

I think we need CustomForm::SubmittedAnswer only as per title of the issue.. I got confused with description mentioning CustomForm::Answer. Will go ahead and create PR accordingly.

**Comment by kasugaijin** [comment]
Yes my bad! Thank you for flagging this. It should be CustomForm::SubmittedAnswer
