### ISSUE TITLE
Merge OrganizationProfile into Organization

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#848]
Merge `OrganizationProfile` into `Organization`. This will require a refactor of models, controllers, views, policies, tests and tables to update the names and method names used. 

We also want to delete the Organization Profiles table, and add the attributes to the Organizations table (donation_url, email,         facebook_url, instagram_url, phone_number) and the applicable model logic for each.

In doing so, we also need to change the association with the Location model; an Organization should have_many locations, and a Location should belong_to an Organization (foreign key).

Ask any questions below!

**Comment by sarvaiyanidhi** [comment]
Hi @kasugaijin I can take up this issue. Can you please assign it to me? Thanks

**Comment by kasugaijin** [comment]
@sarvaiyanidhi all yours
