### ISSUE TITLE
Non-org Root Page - Nav, Hero and Website Snapshot

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#860]
The non org root page will be the root page of the entire application, with an intended audience being anyone wanting to learn more about the app and why they should use it. 

This task is to build the first four major elements  - navbar, Hero, benefits and website snapshot section.

![Image](https://github.com/rubyforgood/pet-rescue/assets/95949082/9e9b6236-6bfa-4815-9ee2-d8b2802f66d9)

See the figma file for more detail, and to export the assets for each section: https://www.figma.com/design/0jVgYASUJy0KiX3BVc3dFM/Tasks?node-id=0-1&t=1y1CCQdxmlBq6wPo-1

Ideally, we do not implement any custom CSS. All design and UI elements should come from the Geeks theme, the Figma assets, and using Bootstrap. 

Geeks theme: https://geeksui.codescandy.com/ - look around here - this is the theme we have built the app with so far

The second issue to build the rest of this page is at: https://github.com/orgs/rubyforgood/projects/16/views/1?pane=issue&itemId=69603848, and is blocked until this issue is merged

**Comment by atbalaji** [comment]
Is this issue still open @kasugaijin ? I would like to work on this. Also the link to the second issue mentioned at the end is unavailable it seems

**Comment by kasugaijin** [comment]
Great, @atbalaji I will open up that second issue once this is merged (that link is to our projects but I don't think you have access to it).

**Comment by kasugaijin** [comment]
@atbalaji how's this going?

**Comment by ErinClaudio** [comment]
@kasugaijin 

I have a few questions before starting this task. Could we break it into four parts of an epic: navbar, Hero, benefits, and website snapshot?

Since I haven't used Figma before, it might take me some time to get up to speed.

Will I be adding these four elements to the page/image shown in this ticket, or should I build on the current root page on the main branch? 

Thank you for the clarification to use Geeks CSS for this.

Thank you!

**Comment by kasugaijin** [comment]
For sure! We can break this down into separate PRs like you suggested. 

#Will I be adding these four elements to the page/image shown in this ticket, or should I build on the current root page on the main branch?

The current root page is just a placeholder, really. I think you can build off of the existing navbar, and within the existing hero section, but thereafter I think you are starting net new on each section. 

Note that the Hero in the figma refers to animated hero text. For this PR, do not worry about any animation, just static text per the Figma is fine.

**Comment by ErinClaudio** [comment]
I am going to be out of town till Friday and will pick this up next week.

**Comment by Aaryanpal** [comment]
@kasugaijin Starting With this.
Please Assign

**Comment by kasugaijin** [comment]
@ErinClaudio we will have some more issues after the meeting today
