### ISSUE TITLE
Refactor CustomForm::SubmittedAnswer to FormAnswer

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#867]
** You can start this but one of the associations cannot be made until this PR is merged (which is close) https://github.com/rubyforgood/pet-rescue/pull/856/files**

After some small architectural decisions requiring changes, we need the SubmittedAnswer model to be removed from the CustomForm scope and renamed to FormAnswer. We also need the submitted_answers table to be named form_answers. Also, please update all references to the class name and methods throughout the code. Basically a find and replace exercise for part of this work.

We should also update the associations on the model:
- has_one :organization, through: :submission
- Get rid of  belongs_to :question
- Get rid of  has_one :form, through: :question
- Belongs_to FormSubmission (blocked until above PR merged)

**Comment by Gabe-Torres** [comment]
Can I take this one?

**Comment by kasugaijin** [comment]
@Gabe-Torres all yours!

**Comment by kasugaijin** [comment]
@Gabe-Torres quick update - I think we should stick to using `acts_as_tenant(:organization)` here (like we do on all other records) instead of making a belongs_to org through submission.
