### ISSUE TITLE
CSV upload: write a CSV import service

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#869]
We need to be able to import a CSV of third party form data containing adopter responses to questions. We will need to be able to match a Person in the app with a row in the CSV using an email address, and then save a new FormAnswer record for each question and answer - we will save the question and the answer on the record. All of the FormAnswers will belong to a single FormSubmission record, which acts as a binder for all of the FormAnswers, representing a submission of data at a given time. 

Note that we need to be able to determine if a given row has already been imported. If it has, we skip it. If it has not, we import it if there is a matching Person. To be able to determine if we have already imported, we need to investigate a little into what data is provided in form CSV outputs by common services like Google Forms. We might be able to use a date/timestamp and save that on the FormSubmission...if a person has a FormSubmission with a given timestamp, we skip that row. If not, we treat it as a new submission and import it. 

Ask away with questions! Note that the FormAnswer model still needs to be renamed (issue https://github.com/rubyforgood/pet-rescue/issues/867)

**Comment by jmilljr24** [comment]
I took a peak at this and a couple of questions came to mind. Looking at a sample Google Form csv, I think checking the db for a person and datetime (timestamp from row) will be the easiest solution. 

1. Will FormAnswer belong to User or Person? FormSubmission is indexed on Person but I don't see that change listed for FormAnswer in #867 .
2. Person query based on email could have issues based off of how the email was entered/saved in the csv (case sensitivity). I know it can be dealt with in the query but I'm not sure if that's the best solution. Here is a [quick read](https://www.mikecoutermarsh.com/storing-email-in-postgres-rails-use-citext/) on some options.

**Comment by kasugaijin** [comment]
@jmilljr24 yes FormAnswer will belong to Person. I think that issue to update FormAnswer is currently in the hopper and was blocked by the creation of form submission because it also belongs to that. That should now be unblocked so I will make the issue. This Csv service will be blocked until that is done…but certainly there’s a lot that can be done before then too.

I didn’t think about email case in the db so I appreciate you bringing that up. We should select an appropriate solution on our call!
