### ISSUE TITLE
Add Filter to Default Pet Tasks page

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#886]
Default Pet Tasks are used to create a list of tasks that get automatically created on a new pet. These tasks can apply to all pets, or a specific species. We render these tasks in a table - sign in as staff, go to dashboard, go to Default Pet Tasks. 

It would be handy to have a filter so we can filter these tasks on Name, Species, Due After, and Recurring. Please use the same UI design as we do for the Fosters and Adoption Application Reviews page.

**Comment by ErinClaudio** [comment]
@kasugaijin 
little help here, please.

is the page below of the tasks page you would like filtered?


<img width="1424" alt="Screenshot 2024-07-23 at 2 45 34 PM" src="https://github.com/user-attachments/assets/a6216672-f182-4f83-9adf-2e7fc4e001a0">

if so within the box shown below would you like to 

- show all those filters or 
- after clicking on the tasks you would like the list of dogs below to have a filter

<img width="293" alt="Screenshot 2024-07-23 at 2 47 11 PM" src="https://github.com/user-attachments/assets/0bd0484f-f782-4eba-b640-09287e6f7377">

**Comment by kasugaijin** [comment]
Hey @ErinClaudio 

This is for the Default Pet Tasks page at `/staff/default_pet_tasks`. You can see this page if you log in as as staff and then go to the dashboard and click the Default Pet Tasks link in the navbar. 

The filter should look like the one we use for adoption application reviews page `/staff/adoption_application_reviews`

**Comment by ErinClaudio** [comment]
It would help if I read the ticket correctly. Thank you

**Comment by ErinClaudio** [comment]
Got it - I will take this one as long as that is ok.

**Comment by ErinClaudio** [comment]
[start](https://gist.github.com/ErinClaudio/ff166c442dcb7fa0bb2e1dca2c8213b1)

**Comment by kasugaijin** [comment]
@ErinClaudio haha no worries. Yes all yours. Please mimick the other filters that use the ransack gem (different from the details provided in your link)
