### ISSUE TITLE
User: add validation for email

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#897]
See the validation used for email on OrganizationProfile (check Organization if that model no longer exists because are removing it) and use the same model validation for User `email`.

**Comment by atbalaji** [comment]
I have applied for another issue @kasugaijin . Here I have a small doubt. Why are we using a custom email regex instead of URI::MailTo::EMAIL_REGEXP ?  Would love to know.

**Comment by kasugaijin** [comment]
The main reason is because that library will allow `a@b` as a valid address...this very issue tripped me up this morning during a design review at work when I entered such an email address and there were no validation issues...and then I wondered why things were not working as I expected...live lol.

So, the current regex we have will capture that. It is not perfect, and email validation gets quite involved, but that regex should capture the bulk of cases and enough for MVP.

**Comment by kasugaijin** [comment]
@sparshalc please comment here in future to get assigned before making a PR. Thanks

**Comment by kasugaijin** [comment]
This PR https://github.com/rubyforgood/pet-rescue/pull/901 has done most of the work - can someone please push this over the line? Thanks

**Comment by Aaryanpal** [comment]
#921 Fixes This Please Close It. @kasugaijin
