### ISSUE TITLE
Adopter Foster Dashboard - update the liked pets design

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#899]
Sign in as an adopter and then like some pets on the adoptable pets page. Then go to the dashboard and look at the Liked Pets link and you will see the liked pets. This issue is just to update the UI to make it look per the image below. Please use the existing avatar component. Please copy over the heart from the existing card along with the turbo stream so it will make the request to unlike or like the pet when you click the heart

![Image](https://github.com/user-attachments/assets/279ea9a5-dcb2-4a49-942b-4a711419943d)

**Comment by ErinClaudio** [comment]
@kasugaijin Happy to start this one once the other is approved.

**Comment by ErinClaudio** [comment]
[Gist](https://gist.github.com/ErinClaudio/001e9862beafa1231578444c9b72a85b)

**Comment by kasugaijin** [comment]
Go for it! I would say for this we don't need to test, actually. So don't worry about that. I am not a fan of tests that couple closely with UI elements as they are a pain to manage when changing the UI at all.

**Comment by kasugaijin** [comment]
Hey @ErinClaudio let's just leave as it is. We can always add in the broadcast later to update the page, but that does add additional overhead (and I suspect some undesirable overhead because it requires we touch a model) and at this stage for MVP it's not necessary.

**Comment by ErinClaudio** [comment]
@kasugaijin 
I believe this can be marked complete per
https://github.com/rubyforgood/pet-rescue/pull/912
