### ISSUE TITLE
AdopterFoster: Add adopted pets to the dashboard

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#900]
We need to enable adopters to go to their dashboard and view their adopted pets and the files associated with those pets. These files get uploaded by staff and are usually things like medical records, so should be shared with the adopter. The adopter should be able to download the files from the dashboard for a given pet.

We need:
- adopted_pets route scoped under org > adopter_fosterer
- adopted pets controller under the same scope
- Index action that displays the adopted pets by that user who is an adopter
- Policy and policy action to make sure the user is an authenticated adopter
- design the pet cards and table per the image below
- see the table in `app/views/organizations/staff/pets/_file_attachment_table.html.erb` except we do not need the buttons to attach or delete
- the icon used for Adopted Pets in the image below is a little dog. We should stick to what's available in our theme at https://geeksui.codescandy.com/ so take a look there and see if you can find something. I was thinking of the star from this dash nav https://geeksui.codescandy.com/geeks/pages/dashboard-instructor.html ... unless you can get a puppy to work without having to upload a new icon...then even better.

For this issue, just get the above working. We will then want to, later, update the table using turbo stream when you click on a pet to render that pet's files. If you really want to do that here, you can as well. I think we should use the show action on the same controller.

design
![Image](https://github.com/user-attachments/assets/76e30755-0692-47c1-b2f0-6ed2e7888d67)

**Comment by sarvaiyanidhi** [comment]
Hi @kasugaijin ,

I can work on this issue.. Can you please assign it to me?

Thanks,
Nidhi

**Comment by kasugaijin** [comment]
@sarvaiyanidhi all yours!
