### ISSUE TITLE
Update Seeds: create a person with each user

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#902]
We added a new `Person` model which will hold all information about a human in the app. The `User` model is now for authentication and authorization only. 

Our seed data currently only creates Users. Please update both seed files for Baja and Alta to create an associated Person for each User that is created.

**Comment by amiii123malviya** [comment]
Hello @kasugaijin ,

I hope this message finds you well. My name is Amisha, and I'm interested in contributing to "Pet-rescue". I came across the issue  #902:Update Seeds: create a person with each user and would love the opportunity to work on it.

I've thoroughly reviewed the contributing guidelines and have successfully set up the development environment. I believe my skills  align well with this task, and I am confident in my ability to address it effectively.

Could you please assign this issue to me?

Thank you for considering my request. I’m excited about the possibility of contributing to this project and look forward to your response.

Best regards,

Amisha

**Comment by kasugaijin** [comment]
> Hello @kasugaijin ,
> 
> I hope this message finds you well. My name is Amisha, and I'm interested in contributing to "Pet-rescue". I came across the issue #902:Update Seeds: create a person with each user and would love the opportunity to work on it.
> 
> I've thoroughly reviewed the contributing guidelines and have successfully set up the development environment. I believe my skills align well with this task, and I am confident in my ability to address it effectively.
> 
> Could you please assign this issue to me?
> 
> Thank you for considering my request. I’m excited about the possibility of contributing to this project and look forward to your response.
> 
> Best regards,
> 
> Amisha

Hi @amiii123malviya for sure this is all yours! Let me know if you have any questions.

**Comment by amiii123malviya** [comment]
Thankyou I will start working on this and will let you know.

Regards
