### ISSUE TITLE
Organization: add null constraints and update org create service

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#913]
Please add null constraints on organizations table in the database for `name`, `slug`, `email` and then update then add email attribute to the Organizations::CreateService when creating an Organization.

Also on the Organization model, we need to validate:
`name` for presence
`slug` for presence and also do not allow any characters that are forbidden in URLs. Look into options for validating this slug.
`email` for format, presence.

**Comment by Gabe-Torres** [comment]
Seems like a fun one! I'll take it

**Comment by kasugaijin** [comment]
@Gabe-Torres all yours!

**Comment by coalest** [comment]
Looks like this task was completed with #918. Can this issue be closed?
