### ISSUE TITLE
Feedback - enable site users to provide feedback to the dev team

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#914]
Add a link with a short description to the Org footer with title 'Feedback' and a sentence saying Click here to let us know about bugs or feature requests' that when clicked takes use to a form where they see a title input and a text area where user can enter information. We should have a header saying something like 'this form is for feedback on bugs and feature requests - thank you for letting us know!'

This form submission sends an email to the dev team email address (TBD).

See the Org contact page for an example of implementation.

**Comment by MooseCowBear** [comment]
I can do this one

**Comment by kasugaijin** [comment]
All yours @MooseCowBear
