### ISSUE TITLE
Staff Dashboard - as staff I can click a link that takes me to a filtered adopter applications review page

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#927]
When you log in as staff and go to the dashboard, you should see an Applications tile with two metrics that show the count of adopter applcations with that given status: X Awaiting Review and X Under Review. When you click on either of these metrics, you should be redirected to the adopter application reviews page and the results should be filtered for that particular status, so that you only see applications with that status e.g., Awaiting Review or Under Review. Let's also place this tile second on the page. 

Tests are not required.

![Image](https://github.com/user-attachments/assets/af7ddfd8-bd8c-4f67-9054-5535a0732f2d)

**Comment by Aaryanpal** [comment]
@kasugaijin please assign will be working on this.
