### ISSUE TITLE
UI: Staff dashboard nav - update order and grouping

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#929]
Let's group the links so that like links live together. 

Move the Dashboard link to the top by itself. 

Rename the 'Menu' nav heading to 'Pets' and under it put:

- Pets
- Adoption Applications
- Fosters
- Default Pet Tasks

Make a new nav heading called 'People' and under it put:

- Fosterers
- Adopters
- Staff

Make a new nav heading called 'Admin' and under it put:

- FAQs
- Forms
- Settings
- Custom Page

![Image](https://github.com/user-attachments/assets/b36b2719-5d9f-478e-b855-2c5a838580e2)

**Comment by Aaryanpal** [comment]
Picking up this @kasugaijin
