### ISSUE TITLE
Render FAQs within the adopter foster dashboard

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#930]
If you log in as an adopter and go to the dashboard you will see an FAQ link. This currently redirects you to another page. However, it should render the FAQs within the dashboard layout like we do with other resources in this dashboard. Please maintain the same UI as on the FAQ page, and please also utilise partials so the view logic is not duplicated.

**Comment by Aaryanpal** [comment]
@kasugaijin I will take this
