### ISSUE TITLE
Adopter application review: When a pet is adopted disable the status dropdown and remove the adopt button

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#931]
Log in as staff and go to the adopter applcation reviews page. The status dropdowns here update via turbostream. If you update one to successful applicant, the new adoption button is enabled, click that and you have made a new adoption. Go back to that adopter application and you will be able to update the status again. This is incorrect. The status dropdown should be disabled if an adoption is made. Also, the new adoption button should be removed if an adoption is made.
No need to add tests.

![Image](https://github.com/user-attachments/assets/5e13dda8-8402-42e7-9aac-997d3d301816)

**Comment by Aaryanpal** [comment]
@kasugaijin please assign this so that i can start.
