### ISSUE TITLE
Donate page: Update design

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#936]
Refactor this view file `app/views/static_pages/_donate_content.html.erb` to match the new design below so it updates the donate view at `/donate` and `/adopter_fosterer/donations`

**We do not need to add the button to learn more about Ruby for Good at this time**

Figma: https://www.figma.com/design/0jVgYASUJy0KiX3BVc3dFM/Tasks?node-id=1299-726&t=THRo8IfbvtFa6az8-1

Image
<img width="916" alt="image" src="https://github.com/user-attachments/assets/c4c7daa9-540c-4429-977a-88647b1a18a8">

**Comment by Aaryanpal** [comment]
@kasugaijin please assign will be working on this
