### ISSUE TITLE
Replace donate page image

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#950]
The donate page image needs to be replaced with one we can use for commercial use. Please remove the current file being used, and replace with this one in Figma https://www.figma.com/design/0jVgYASUJy0KiX3BVc3dFM/Tasks?node-id=1299-726&t=UB0y1iDjXV3r1unQ-1

**Comment by Aaryanpal** [comment]
@kasugaijin please assign this will be working on it

**Comment by Aaryanpal** [comment]
@kasugaijin This Needs to be closed
