### ISSUE TITLE
Add URL param on Staff Dashboard results

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#951]
As staff, if you go to the dashboard and look at the overdue and incomplete pet task tables, they render a Pet. The pet name can be clicked to go to the pet show page, and the count can be clicked to take you to the tasks tab of the pets show page. Let's make the whole row clickable to take you to the tasks tab of the pets show page, instead.

**Comment by sarvaiyanidhi** [comment]
Hi @kasugaijin,

With regards to this issue, I just wanted to highlight that tasks link is already rendered to URL http://localhost:3000/alta/staff/pets/1?active_tab=tasks when we click on count of tasks displayed in table. Just highlighting it as I had worked on this feature earlier. 

Right now in current implements, when we click on pet name it goes to show page and on click of count of overdue or incomplete tasks it goes to pets show page with param active_tab=tasks

Thanks

**Comment by kasugaijin** [comment]
@sarvaiyanidhi  ah I see! Then it would be good to include the URL parameter on all clicks from that table so it always takes the user to the pet tasks tab

**Comment by sarvaiyanidhi** [comment]
Sure.. Will make changes and push it.
