### ISSUE TITLE
Adopter Dashboard: Add empty states

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#955]
Log in as an adopter and go to the dashboard. Click on Adoption Applications and withdraw and delete apps. You will then see an empty table. We should add an empty state, i.e., show the following text in the table `You do not have any adoption applications`

We should also do the same for the Liked Pets and show the following sentence `You do not have any liked pets`

**Comment by Aaryanpal** [comment]
@kasugaijin please assign this
