### ISSUE TITLE
Staff Dashboard: Add card to display foster details

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#962]
As staff, I should be able to go to my dashboard and see a new card called Fosters, that replaces the Pets card. 
<img width="364" alt="image" src="https://github.com/user-attachments/assets/a9a889e2-d349-4f97-a4a9-8ced03e1ccef">

On this card, I should be able to see metrics for:

- number of active fosters i.e., `foster.status == :current` clicking this redirects me to `/staff/manage_fosters` with URL params to filter results with a status of 'current'
- number of upcoming fosters i.e., `foster.status == :upcoming` clicking this redirects me to `/staff/manage_fosters` with URL params to filter results with a status of 'upcoming'

You might note that if I have two upcoming fosteres, the results are displayed with the closest date to now at the bottom, and the furthest date from now at the top. Please switch this ordering so the closest date to now is at the top.

**Comment by basil-gray** [comment]
@kasugaijin Hello, first time contributing. Please assign - I would love to implement this.

**Comment by kasugaijin** [comment]
@basil-gray all yours

**Comment by basil-gray** [comment]
Just updating that I'm still working on this.

**Comment by basil-gray** [comment]
The ordering seems to be off when there's a mix of current and upcoming fosters.

![image](https://github.com/user-attachments/assets/de6fefe2-5cbe-4f23-a36e-8efbeb84cbe1)

1) Should the different statuses be grouped together in a specific order? Personally I think as a staff, it would be useful to see the current fosters grouped at the top, upcoming in the middle, and completed at the bottom. Each group would then be in ascending order.

2) Should we allow the user to create more than one current foster? Not sure if there's a use case for this.

3) Changing the start date and end date on the manage fosters page seems to break the update endpoint. Is there an issue for this? I can raise it if not.

![Screenshot 2024-09-16 at 00 57 38](https://github.com/user-attachments/assets/2ea516f7-e977-4a2e-a846-b135d10f8b37)

**Comment by kasugaijin** [comment]
Hey @basil-gray thank you for the questions!
> Should the different statuses be grouped together in a specific order? Personally I think as a staff, it would be useful to see the current fosters grouped at the top, upcoming in the middle, and completed at the bottom. Each group would then be in ascending order.

Yes, I agree with this approach. 

> Should we allow the user to create more than one current foster? Not sure if there's a use case for this.

Good point. This is a bit of an edge case I think. Currently we let a staff create a foster Match that could have the exact same dates, or overlapping dates, and for a period of time, both foster Matches would be 'current'. For now, I think this is OK. Let's test this out in production with a real user and get feedcak to determine the correct way to handle this.

> Changing the start date and end date on the manage fosters page seems to break the update endpoint. Is there an issue for this? I can raise it if not.

Ah nice catch. Looks like the I18n is causing an error. 'Should' be a simple fix. Please do make an issue for this!
