### ISSUE TITLE
Staff Dashboard - Fix pet filter for status

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#969]
Log in as staff and go to the dashboard > pets and you will see an index of pets. Add a filter e.g. `unadopted` and you will note that in the results there will still be adopted pets. This is incorrect. Please fix this and check the other filters work as expected.

**Comment by khiga8** [comment]
Can I pick this up?

**Comment by kasugaijin** [comment]
@khiga8 for sure
