### ISSUE TITLE
Staff Pets: Add badges so staff can tell if a pet has been adopter, is in foster, or open

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#970]
We have a badge component that already tells people if an adoption is pending on a pet. 
![Image](https://github.com/user-attachments/assets/05e3d702-128a-4716-bd80-d9b25caec9b6)

Use this badge component to create three new badges for 
- adopted (`bg-light-success`)
- in foster (`text-white bg-dark-primary`)
- open (`bg-light-warning`)

Add this badge to pets index table/mobile card for staff - replace the sex column with a 'status' column and place the badge.
![Image](https://github.com/user-attachments/assets/42df6ed5-e7f1-47fe-a8bc-362da4704a5a)
 
Add this badge to the pets show page next to the pet name
![Image](https://github.com/user-attachments/assets/9216e59e-3dfc-4243-92d9-b60a4725d419)

Given that this view logic will be used in more than one place, it probably makes sense to use a Helper, something like `PetBadgeHelper` or the likes

**Comment by italomatos** [comment]
Hi @kasugaijin ! can I do this one?

**Comment by kasugaijin** [comment]
For sure! @italomatos
