### ISSUE TITLE
Staff: Remove toggle to cards for the People features

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#971]
We currently have a toggle for staff to convert table rows to cards, and back. We should remove this toggle feature and instead convert to cards based on screen width i.e., convert to cards for mobile, like we do for all other pages. Please do this for the Staff, Adopters, Fosterers pages on the staff dashboard.

![Image](https://github.com/user-attachments/assets/21cf9b0e-93d8-4ca4-b567-4b2a23ca94e5)

**Comment by italomatos** [comment]
Hi @kasugaijin ! can I do this one?

**Comment by kasugaijin** [comment]
@italomatos all yours

**Comment by italomatos** [comment]
https://github.com/rubyforgood/pet-rescue/pull/972 

This is my first time contributing to the project. I’m sharing the link to the PR here, should I request someone to do a code review ? 

Thanks
