### ISSUE TITLE
Update endpoint throwing wrong arguements error

### ISSUE THREAD

**Issue by basil-gray** [rubyforgood/pet-rescue#980]
On the manage fosters page for a staff, changing the start date will cause the shown error.

![image](https://github.com/user-attachments/assets/0e025520-50fe-4215-ada4-cce22343b2d6)

![image](https://github.com/user-attachments/assets/575ef642-2f58-4a65-bb47-5b31cfe4eef7)

**Comment by MarchandMD** [comment]
I'm on FF and not necessarily able to reproduce this error...

https://github.com/user-attachments/assets/1c096f48-eee7-432c-a652-0a09b9492bf7

**Comment by basil-gray** [comment]
@MarchandMD Thanks for checking. I'll have a look at this again tonight.

**Comment by basil-gray** [comment]
I can't seem to reproduce this anymore with the latest changes from main. Weird.

Closing issue.
