### ISSUE TITLE
Staff Dashboard - add breadcrumb and remove subtitles

### ISSUE THREAD

**Issue by kasugaijin** [rubyforgood/pet-rescue#985]
Sign in as staff and go to the dashboard
Please add the breadcrumb to Adoption Applications page - you will see it is missing
Please remove the subtitles from the Settings and Custom Page pages.

**Comment by Aaryanpal** [comment]
@kasugaijin Please allow me to continue working on this as a change
#885 is requiring more time than initially anticipated

**Comment by Aaryanpal** [comment]
@kasugaijin This Needs to be closed
