### ISSUE TITLE
Staff Dashboard: make cards have the same dimension 

### ISSUE THREAD

**Issue by DreamVenerable** [rubyforgood/pet-rescue#992]
As staff go to the dashboard. You will see that the cards for Adoption Applications and Fosters are different sizes.
When switching between them you will notice it's not fluid to the eye.

The below image shows both views being layered on top of each other:
![imglayer](https://github.com/user-attachments/assets/ab3029bd-562f-4eb7-bb24-501e9e85507e)

**Comment by MichaScant** [comment]
Hey, first-timer here, is it alright if I take this issue?

**Comment by DreamVenerable** [comment]
Hey @MichaScant, unfortunately I also don't have permission to assign, you'll have to wait until someone who does to take this.

**Comment by kasugaijin** [comment]
@MichaScant all yours!

**Comment by Aaryanpal** [comment]
Hey @DreamVenerable, 
that's an impressive catch! I'm curious, how did you manage to do that?

**Comment by DreamVenerable** [comment]
Hey @Aaryanpal, I was just going through the pages, I might have noticed it due to OCDness. 😆
